### ISSUE TITLE
[E-Mail functionality] Secondary Mail address consideration 

### ISSUE THREAD

**Issue by kebechsenuef** [jobisoft/CategoryManager#10]
In case of the Mail function use (btw: great feature) > only "main" Mail adresses are accepted and will be used in the prepared E-Mail. Perhaps its possibile to consider also the secondary Mail parts?

![01](https://cloud.githubusercontent.com/assets/6011872/15305668/b4d42412-1bc4-11e6-8a23-5f157220c3de.png)

![02](https://cloud.githubusercontent.com/assets/6011872/15305670/b86ce8b6-1bc4-11e6-920e-507e344da8e3.png)

**Comment by jobisoft** [comment]
Also wenn keine primäre Email angegeben, dann soll er die alternative Email nehmen? Und wenn beide angegeben sind, dann nimmt er die primäre? Ja, das geht, kommt in v2.02.

**Comment by jobisoft** [comment]
fixed in v2.02

**Comment by kebechsenuef** [comment]
Thanks!
