### ISSUE TITLE
Error: We have a card without ID (groupDavKey): Name

### ISSUE THREAD

**Issue by karstengit** [jobisoft/CategoryManager#11]
Please refer also to http://sogo.nu/bugs/view.php?id=3691

I am using the backend sabredav as CardDAV server.
I must deactivate the CategoryManager, otherwise i get for every entry of an remote addressbook this Error when i open it.
The errors will disappear when i deactivate the CategoryManager.

**Comment by jobisoft** [comment]
This is on my current to-do-list. CategoryManager uses lots of sogo stuff, for example the groupdavid to filter for categories. I assumed, that every card which has been pushed by sogo to the server gets a groupdavid, which i use to find/filter cards. Thats why this check is there. It will be removed in CategoryManager 2, which I am working on right now (and which is not using groupdavid or any sogo stuff at all).

However, if that check fails, I do think something is wrong with the sogo sync state. Can you verify, that the reported cards are indeed available on the server and not just in your local Thunderbird? How did you import these "bad" cards into the adressbook?

**Comment by karstengit** [comment]
The problem only occur on addresses that are stored remote with CardDAV.
I imported a complete telephone book from VCF format.
This import is stored as local addressbook in Thunderbird.
When i move with drag and drop an address to a remote addressbook via CardDAV then the address / VCF is definitely stored there. I can see it in the database.
When i reopen this remote addressbook again i get this error for every entry.
When i export one address as VCF and import it again the error has gone.

Yesterday i created a few new addresses with deactivated CategoryManager.
Today there is no problem when i activate it.
I tried to reproduce the error but now i could move an address without problem.
It's not easy to say what has happened.

The cards are stored in MySQL with two ID's - here an example:
uri: C715A793-7830-0001-39DF-168017505530.vcf
etag:  cb277fce6348ebde763ffc87f1527041
Do you know what this ID's are good for?

**Comment by jobisoft** [comment]
This is fixed in v2.01
