### ISSUE TITLE
Preinstalling shows 'null ' as AddOn Name

### ISSUE THREAD

**Issue by marneu** [jobisoft/CategoryManager#13]
If you deploy Tb with provisioning and preinstalled AddOns, the title for this AddOn will show 'null' as name.
Unfortunately this AddOn needs to be installed manually/separately.

**Comment by jobisoft** [comment]
Any Idea what I can do about that? What part of the source needs to be changed? Do you know of an addon, that does not have this problem, so I can compare?

What "title" at what location inside TB shows "null" as name?
Is the category manager still working even if that title is "null"?

Deutsch ist auch ok.

**Comment by marneu** [comment]
Sorry for late reply!
Unfortunately I do not know how to implement that, but working example could be "Inverse SOGo Connector" which is used in the same way a I'd like to use your AddOn.

**Comment by jobisoft** [comment]
Ok, I need to reproduce the issue first. What steps do I have to take, to deploy TB with preinstalled AddOns as you did?

**Comment by marneu** [comment]
It might be easier to talk on phone or an alternate ... any idea? Something like PM

**Comment by jobisoft** [comment]
You could write me an email if that is easier for you (my address can be 
found here: https://github.com/jobisoft).

Phone will not work.
