### ISSUE TITLE
[MFFAB] Categories not recognzed by CategoryManager

### ISSUE THREAD

**Issue by webdb22** [jobisoft/CategoryManager#14]
A very useful idea, unfortunately it doesn't work for me. Only a part of the existing contacts are listed as "members" for the respective "category name" in "Found categories". Checking the contacts I found the categories partly out of sync comparing the new Tab "Categories" added by "Category Manager" and the standard Tab "Other Data".

Creating a new contact and adding categories via the "Other Data" Tab are nor recognized by the "CategoryManager" and categories entered in the "Categories" Tab are not displayed in "Other Data" Tab.

This might be related to a different naming, I've seen the column "Category" as well as "Categories" in the export generated by CategoryManager?! Or does it interfere with "MoreFunctionsForAddressBook"?

Software:
 - Thunderbird V45.6.0
 - CategoryManager V2.0.4
 - MoreFunctionsForAddressBook V0.7.5

**Comment by jobisoft** [comment]
Yep, MoreFunctionsForAddressBook (MFFAB)  is adding its own Category 
Management. The Category Manager is not using/touching these categories. 
As you have pointed out, I am using the "Categories" field and MFFAB is 
using the "Category" field.

If you simply ignore the "Other Data" Tab and manage all categories with 
the Category Manager, these two Addons should work side by side without 
harm.

**Comment by webdb22** [comment]
Thanks for the prompt reply! Understood, makes sense.

It is kind of irritating to have two types of "Categories", Is there a chance to make the experience more seamless and user friendly, e.g. have a setting (at install time?) to switch between:
  a) Default Mode: "CategoryManager" uses the default "Categories" field and its own Tab "Categories"
  b) MFFAB Mode: "CategoryManager" uses the "Category" field and only the "Other Data" Tab shows the categories
All the other functionality and UI could stay the same, just an additional setting to switch between these two?!

**Comment by jobisoft** [comment]
I don't see how that could work out. I cannot simply use (and write to) 
the "Category" field because than I would interfere with MFFAB. Also 
lots of other internal stuff would break.

If you have used MFFAB so far and thus have lots of categories stored in 
the Category field and want to switch to CatMan for managing categories, 
I could add a migrate option, which moves all data from the category 
field to the categories field. After migration, I could also hide the 
category edit option in the "others" tab of MFFAB, so no one gets 
confused with multiple but different category edit options.

Just for my understanding: Is there any category related feature in 
MFFAB, that is missing in CatMan?

John

**Comment by webdb22** [comment]
Thanks for the explanation, makes sense! I had assumed that this wouldn't be an easy task, but it was worth a shot!

A clean migration / synchronization (merge all categories from MFFAB into CatMan and vice versa) would be great, maybe also being able to re-sync on request if some other tools / plugins write / use the "other" category field.

Making sure only one category edit option is available (by e.g. hiding others) would surely improve the user experience.

I've been using MFAAAB for years now (not only for category related stuff) so I'm quite used to it. I like the the pop-up which lets you easily select multiple categories from a sorted list and add / remove / rename categories. Also the condensed view in the tab is nice, although I'd prefer a entry similar to e.g. a list of tags, or the entry of an email address in Thunderbird with auto-complete and just a semicolon (";") as separator.

What I'm currently missing from CatMan:  
- Being able to use "Categories" in the filter, similar to filter on "Name" or "Notes"
- Being able to add "Categories" as a column in the list view

Some suggestions for usability improvements for the current CatMan:
- Keep the category highlighted when selected (in the "Found Categories")
- Improve upper / lower case spelling in the labels and buttons (should be e.g. "Members",...)
- Add buttons to remove and rename selected categories (besides the "Add Category")

Please don't see this as disrespect of your work on CatMan, just my two cents regarding improvements...

**Comment by jobisoft** [comment]
OK, I will append this to my todo list. I am currently working on another project, which consumes most of my time, so it will take a while. As english is not my native language, any help on the locale stuff is appreciated :-) 

If you have time, you could go through these two files:

https://raw.githubusercontent.com/jobisoft/CategoryManager/master/sendtocategory/locale/en-US/catman.dtd
https://raw.githubusercontent.com/jobisoft/CategoryManager/master/sendtocategory/locale/en-US/import-export-wizard.dtd

You could send me the updated files via email or simply clone my project and send the changes as a pull request.  If you do not have time for this, please do not feel any pressure.

Thanks for the suggestions!

**Comment by webdb22** [comment]
Hoping you'll find some time sooner rather than later! ;-) Would make Category Manager more useful! 

I've reworked the two files you've mentioned (see attached), don't assume them to be perfect, but at least some spelling and wording mistakes should be gone by now. It's a little bit hard to do this without the context, but it should be sufficient. You might want to check the spacing in and around the special tags like "##  ... ##" and "{{ ... }}", looks a little bit odd to me.

[catman_dtd_V2.zip](https://github.com/jobisoft/CategoryManager/files/690808/catman_dtd_V2.zip)

**Comment by mjgreis** [comment]
Hi. I just installed CatMan and ran into this issue as well, having used MFFAB for some time.  I echo webdb22's comments and suggestions, and would certainly like to see a migration option as well.  I only dabble in coding, so I can't offer much help.  My German is rusty, so although I could offer to help with language, I'm not sure how effective I would be.  

I do have one question, however.  I use MFFAB to extract entries from my address book to a CSV file.  The fields it extracts includes "Category".  Does this mean that CatMan's categories would not be exported?  Are there other add-ons that would extract CatMan's categories?  (Are there others that allow more control over which fields are exported?).  

Thanks!

**Comment by jobisoft** [comment]
Hi!

I tried to reach out to the developer of MFFAB but he did not respond. No help from there (and no future development?)

I WILL take over some of his functions (as I did with the import/export already), the next will be the extra category column in the addressbook view. What I could also do with low effort is a hard migration: Move(!) all categories from the CATEGORY field (MFFAB) to the CATEGORIES field (CatMan). Tell me, if this would help you.

@mjgreis: CatMan has its own export function which exports the CATEGORY and the CATEGORIES field, if I remember correct.

**Comment by bege10** [comment]
Hi,
came across this thread after having installed CM 2 2.04
I also use MFFAB and second the mentioned issues above.
As long as CM is in development I prefer to COPY all categories from MFFAB to CM.

You mention the export function of CM. I find the export function of MFFAB in the Extras menu and the context menu. Where do I find this function of CM?

**Comment by jobisoft** [comment]
The export function of CatMan is a bit hidden: In the left "Categories" 
pane in the address book, if you right-click on a category, you can 
export that category. If you click on "all", you can export the entire 
adress book.

Could you find it?

At the moment all my time goes into another addon 
(https://github.com/jobisoft/TbSync), but at some point I will add the 
function to copy/move categories from MFFAB to CatMan.

**Comment by bege10** [comment]
Thank you.

**Comment by jobisoft** [comment]
ok, I did work on this:

- MFFAB categories are now displayed inside my category lists (left pane in the address book and in the category list of the F9 menu when writing an email)
- MFFAB categories have a " (MFFAB)" appended to their name
- MFFAB categories can only be used as category based contact groups - renaming, deleting, edit and export is not possible. Renaming and deleting might be possible, bulk edit and export require a lot of work which I am not willing to do
- the context menu of MFFAB categories provide an option to convert them to standard categories

I will not touch MFFAB GUI elements.

Feedback would be great.

**Comment by jobisoft** [comment]
Added a beta relase:
https://github.com/jobisoft/CategoryManager/releases/tag/v2.05-beta1

**Comment by jobisoft** [comment]
I am not happy with that solution, mixing both category types does not feel right. Here is an alternative implementation, where (as webdb22 suggested) the seperator and category field is switched to MFFAB mode. Thus displaying either CatMan categories or MFFAB categories.

https://github.com/jobisoft/CategoryManager/releases/tag/v2.05-beta2

The option can be found at the "Category Manager" options panel at "Options". Using this option makes CatMan an extension to MFFAD.

Where to go?

**Comment by jobisoft** [comment]
Sadly no feedback. I trashed beta1 and continued to work on beta2 which is now released as v2.05.

https://github.com/jobisoft/CategoryManager/releases/download/2.05/CatMan-v2.05.xpi

- if MFFAB is installed, context menu in category pane has two more entries ("switch category mode" and "convert category")
- if MFFAB is installed and user has no "Categories" entries (standard CatMan) but only "Category" entries (MFAAB), the MFFAB mode is silently enabled.
- the MFFAB option is no longer to be found in the Thunderbird settings (no one goes there anyway), but only in the context menu of the category pane.

I consider this done. Still feedback would be nice. Also a donation, to motivate me to continue to implement user requests I actually do not need for myself.

**Comment by mjgreis** [comment]
Thanks so much for doing this work.  I am an MFFAB user and got on this thread because I was interested in CatMan for its features.  Since I'm not a current CatMan user, I have to install the new CatMan, make sure nothing vital to my (real) work gets lost, and then do enough testing before I could offer any intelligent feedback.  Unfortunately, I just haven't had a moment to do that yet.  I hope to, though, and will report back when I do.

**Comment by bege10** [comment]
Sorry for my late response, I was not at my computer for some days.
Thank you very much for your work on this issue!

- Switching the modes works very well, having all categories in my contacts now in the CatMan window
- In Standard mode I cannot delete categories (greyed out)
- In MFFAB mode I cannot convert a category to Standard category (greyed out)
- If I want to completely change from MFFAB to CatMan, can I convert all MFFAB categories to CatMan categories in all contacts?

**Comment by jobisoft** [comment]
greyed out means, you have selected the global address book (which sums up all your individual address books). Is that correct? What happens if you select an individual book?

Yes, you can convert all catagories one by one to standard (and back to MFFAB if you wish) without loss of information. I am thinking about adding a "convert all" option for this...

**Comment by bege10** [comment]
You are right, if I select a single address book all options are available. Great!
I think you found a very good solution. Switching between the two modes, converting categories between the modes. And a "convert all" option would make it perfect.
Thank you very much.
This addon is really worth a donation   :smiley:

**Comment by jobisoft** [comment]
Thanks. 

I could add the "convert all" option as a third special MFFAB entry at the bottom of the context menu, but this would make it very long. Does it make sense to use the convert entry of the "all" category (the top most category entry) for this purpose (its label will then of course say "convert all categories")?

Would you search for that option there, if you did not know about it already? 

I did re-use the context menu entries of the "all" category already, for example to export the entire address book and not just a single category.

**Comment by bege10** [comment]
I think it makes sense to use that entry because it is greyed out at the moment anyway.
Well, I didn't look for the options in the context menu at all, you first hat to tell me in a post above  :smirk:
But if you give a description on the AMO page this is fine.

**Comment by jobisoft** [comment]
ok, here is an updated release, with convert-all-option available at the "all" category entry:

https://github.com/jobisoft/CategoryManager/releases/download/2.05/CatMan-v2.05.1.xpi

The global address book still has most entries in the context menu disabled, which is a different issue, which i might get fixed later.

What I am still thinking about: The entry "switch to MFFAB category mode" (and back) are not "per category" options and thus should not be located inside the category context menu, but rather as an additional button somwhere above or below the category list. Any thought on that?

**Comment by jobisoft** [comment]
uups, bugfix:

https://github.com/jobisoft/CategoryManager/releases/download/2.05/CatMan-v2.05.2.xpi

**Comment by bege10** [comment]
Thank you very much!
The context menu of both all and single category says (in German locale, re-translated) "convert **all** categories to standard categories"

**Comment by bege10** [comment]
> What I am still thinking about: The entry "switch to MFFAB category mode" (and back) are not "per category" options and thus should not be located inside the category context menu, but rather as an additional button somwhere above or below the category list. Any thought on that?

You are right that this might not look "perfect", but I am fine with it as it is now. I don't think anyone will misunderstand.

**Comment by jobisoft** [comment]
fixed wrong label, also played around with a "MFFAB mode slider"

https://github.com/jobisoft/CategoryManager/releases/download/2.05/CatMan-v2.05.3.xpi

**Comment by bege10** [comment]
You made it perfect  :smirk:
Thank you.

**Comment by jobisoft** [comment]
I keep this issue open for another week or two and if there are no 
further bugs, I will close it and push the new version to the official 
Mozilla repository.

**Comment by jobisoft** [comment]
This is going to take longer. If the user has the SOGo connector installed, there is a glitch which will cause data loss. I cannot release v2.05, before SOGo fixed the bug. I have a pull request open.

https://github.com/inverse-inc/sogo-connector.tb31/pull/26

Furthermore I got feedback, that the "Categories edit tab" in the card edit dialog should always edit the Categories property (the original Category Manager category) and should not switch over to edit the MFFAB categories if MFFAB mode is enabled (as it is doing now). The tab will also get a description, to inform MFFAB users, that this tab is not showing MFFAB categories (but the 'Other data' tab does).

Anyhow, DO NOT USE  v2.05 if you also have the SOGo-Connector installed, you may lose data. I report back, if SOGo pulled my changes.

**Comment by bege10** [comment]
Without SOGo connector no problems so far.

**Comment by jobisoft** [comment]
I fixed all reported bugs and display glitches and also added a fixed version of the SOGo-Connector, so you can test Category Manager 2.05 without loosing data.

https://github.com/jobisoft/CategoryManager/releases/download/2.05/CatMan-v2.05.4.xpi
https://github.com/jobisoft/CategoryManager/releases/download/2.05/sogo-connector-31.0.4jb.xpi

**Comment by jobisoft** [comment]
SOGo accepted my fix. I now have to wait until a new version of the sogo-connector including my fix has been released. After that, I can officially release a new version of the CategoryManager including the new MFFAB features.

**Comment by bege10** [comment]
Thank you for your work!
