### ISSUE TITLE
[gContactSync] Adressen und Kategorienimport aus Google - sehe im einzelnen Datensatz keine Kategorien

### ISSUE THREAD

**Issue by oemm1** [jobisoft/CategoryManager#15]
Nach dem Import der Daten aus Google finde ich zwar die einzelnen Kategorien und darin auch die jeweiligen Adressen, jedoch wenn ich eine Adresse öffne, sehe ich nicht die zugehörigen Kategorien.

Toll wäre auch, könnte man bei der Einstellung der Spalten der Spaltenansicht im Adressbuch auch die Spalte "Kategorien" anwählen. So sähe man im Überblick sofort, wer welchen Kategorien zugeordnet ist und wer nicht.

Oder gibt es einen anderen Approach mein Problem der Kategorieüberprüfung bei bestehenden Daten zu erfüllen.

Habe ich etwas falsch gemacht oder vergessen?

Danke sehr!

Mit freundlichen Grüßen aus Wien!

Michael
OE-MM1

**Comment by jobisoft** [comment]
Hi Michael,

auf der Add-On-Seite gibt es ein paar Bilder, die die diversen 
Möglichkeiten zeigen, wie und wo Kategorien vom Category Manager 
angezeigt bzw. bearbeitet werden können:

https://addons.mozilla.org/de/thunderbird/addon/categorymanager/

Alternativ gibts die Bilder auch hier:

https://github.com/jobisoft/CategoryManager/tree/master/screenshots

Kannst du mir sagen, welches Bild sich nicht mit deinem System deckt, 
also wo die Kategorien nicht wie erwartet angezeigt werden?

Kannst du evtl auch kurz auflisten, welche sonstigen Add-Ons du benutzt, 
um Inkompatibilitäten zu finden bzw. zu erkennen? Wie genau hast du die 
Kontakte aus Google importiert?

Die Sache mit der extra Spalte ist für 2.Quartal 2017 geplant.

Grüße,
John



Am 13.01.2017 um 21:03 schrieb oemm1:

**Comment by oemm1** [comment]
John, danke für Deine schnelle Antwort!

Meine Add-Ons:
![verwendete add-ons](https://cloud.githubusercontent.com/assets/21205156/21962279/49ad9092-db22-11e6-97a4-51dd3844d9ef.png)

Ich verwende Linux und da sieht alles anders aus! Jedoch fällt mir folgendes auf:
1) Es werden auch in der Übersicht keine Kategorien angezeigt:
![keine kategorien](https://cloud.githubusercontent.com/assets/21205156/21962631/aa86699a-db2a-11e6-984a-82a905083b40.png)

2) Im einzelnen Datensatz gibt es ebenso keine Kategorien.
![im datensatz keine kategorien](https://cloud.githubusercontent.com/assets/21205156/21962658/73a24ed4-db2b-11e6-98b2-c2e9fba000f3.png)

Insgesamz habe ich sicherlich 10 Kategorien vergeben, welche in den Gmail Kontakten auch zu sehen sind.

LG

Michael

**Comment by jobisoft** [comment]
Hm, kann ich mal ein Bild sehen, wo Kategorien tatsächlich zu sehen sind?

Grüße
John


Am 15.01.2017 um 14:04 schrieb oemm1:

**Comment by oemm1** [comment]
Wenn man im Adressbuch nach Emails sortiere, kommen zuerst die Kategorien (als Verteilerlisten):
![die kategorien](https://cloud.githubusercontent.com/assets/21205156/21964000/f34e2d52-db43-11e6-8a49-b5c1cb17ad2c.png)

**Comment by jobisoft** [comment]
Ok,

du hast also gar keine Kategorien mit Hilfe des Category Managers 
angelegt, sondern hast "nur" mit gContactSync deine Google Kontakte nach 
TB synchronisiert. Die Google-Kategorien (die du irgendwie in der GMail 
Web Oberfläche angelegt hast) werden augenscheinlich von gContactSync 
als Verteilerlisten nach TB synchronisiert, nicht als echte Kategorien 
(du siehst diese Verteilerlisten auch ohne installierten Category Manager).

Da die Kategorien an sich ja synchronisiert werden, nur eben nicht so, 
wie der Category Manager das braucht, sollte es technisch möglich sein, 
die Google-Kategorien auch als echte Kategorien zu synchronisieren. Ich 
werde mich mal mit dem Entwickler von gContactSync in Verbindung setzen, 
weil das jetzt schon die zweite Anfrage in diese Richtung ist. Ob sich 
da was tut, kann ich natürlich nicht versprechen. Es stellt sich aber 
die Frage, ob das nötig ist? (Die Frage wird mir der Entwickler von 
gContactSync auch stellen).

Der Category Manager wurde ursprünglich entwickelt, um eine Alternative 
zu den Verteilerlisten zu haben, die früher sehr störanfällig und auch 
nicht besonders gut zu synchronisieren waren. Heute hat sich da vieles 
verbessert, sodass die Implementierung von gContactSync sehr stabil ist 
und die Google-Kategorien "nativ" in TB genutzt werden können, ohne dass 
dafür ein weiteres Add-On benötigt wird. Du kannst also erstmal mit den 
google Kategorien arbeiten, dazu brauchst du den Category Manager nicht. 
Da ich u.A. aber auch gmail nutze und da auch gerne die anderen Features 
des Category Managers mit meinen gmail Kontakten nutzen möchte, bin ich 
selbst auch an einer entprechenden Umsetzung interessiert. Ich geb hier 
Rückmeldung, wenn ich mit dem Entwickler von gContactSync gesprochen habe.

Grüße
John

**Comment by oemm1** [comment]
John,
danke für Deine ausführliche Antwort!

Originär kommen die Kategorien aus dem Outlook. 
Sie wurden mittels des Windows Programms gSyncit mit Gmail synchronisiert.

Dann kam mein Abschied von Windows.

Thunderbird mit gcontactsync unter Ubuntu ist meine neue Welt.

Solltest Du eine smarte andere Lösung haben, bin ich auch offen!

Übrigens auch für eine Lösung unter Unix für Adressen und Termine weg von Gmail hin zu einem eigenen Server!

Da immer mehr weg von Windows gehen werden, denke ich dass wir beide nicht die einzigen bleiben werden, die an einer smarten Lösung interessiert sind.

Liebe Grüße

Michael

**Comment by oemm1** [comment]
Hallo John,
gibt's Neuigkeiten?

Danke für die Info und liebe Grüße!

Michael

**Comment by jobisoft** [comment]
Ich habe leider keine Rückmeldung vom Entwickler von gContactSync bekommen. Ich versuche es demnächst nochmal.

**Comment by oemm1** [comment]
Ah, danke, dass sie sich gemeldet haben!

Liebe Grüße aus Wien!

M.M

⁣Gesendet mit BlueMail ​

**Comment by jobisoft** [comment]
Closing this, if I ever going to fix this, it will be in my own google provider, which is not yet planned...
https://github.com/jobisoft/CategoryManager/issues/38
