### ISSUE TITLE
Forwarding?

### ISSUE THREAD

**Issue by andreaskoerber** [jobisoft/CategoryManager#16]
Hello,
I really like the category manager.
But is there a possibility to use for forwarding a mail to all members of a category? At the moment I think I can use it only for starting new mails. It would be nice to have a way to use it in the address-field of a mail already existing.
Thx in advance
A

**Comment by jobisoft** [comment]
That is indeed possible. After you clicked on "forward" and the email is opened to be edited, press F9. This opens the contact sidebar. Contacts in this sidebar can be filtered by categories as well and at the bottom you have three buttons to add the selected contacts as TO, CC or BCC.

Please keep (german) data protection in mind and do not add all members of a category to TO or CC, if you do not have the permission of all members to publish their email address. Use BCC.
