### ISSUE TITLE
Keine Kategorien in der Sidebar, wenn darüber "Alle Adressbücher" fokussiert ist.

### ISSUE THREAD

**Issue by bege10** [jobisoft/CategoryManager#17]
Es wäre sehr hilfreich, wenn auch in dieser Ansicht die Kategorien angezeigt würden.
Danke.

**Comment by jobisoft** [comment]
notiert.

**Comment by jobisoft** [comment]
Hast du den SOGo Connector installiert? Was wird bei dir angezeigt, wenn du im normalen Adressbuch das globale Adressbuch auswählst?

**Comment by jobisoft** [comment]
egal, fixed in 2.0.5
