### ISSUE TITLE
Kategorienfenster behält die Position nicht

### ISSUE THREAD

**Issue by bege10** [jobisoft/CategoryManager#18]
Wenn das Adressbuch neu gestartet wird, bleibt das Kategorienfenster nicht in der Position vor dem Beenden. Für mich nimmt es so zu viel Platz ein (gut 3/4 der Sidebar). Deshalb fände ich es wünschenswert, wenn es die Position behält, die vorher eingestellt war.

**Comment by jobisoft** [comment]
Daran hab ich mir schon die zähne ausgebissen. Hier

https://github.com/jobisoft/CategoryManager/blob/master/sendtocategory/content/addressbook/addressbook_overlay.xul#L48

hab ich eigentlich festgelegt, das die Position des splitter persistent 
sein soll,klappt aber nicht so richtig. Wenn das jemand besser 
hinbekommt, immer her damit.

**Comment by bege10** [comment]
Davon habe ich leider keine Ahnung. Deshalb mit ganz großer Vorsicht: Muss man vielleicht statt dem Splitter das Fenster festlegen oder unter "persist" andere Elemente?
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Persistent_Data

**Comment by jobisoft** [comment]
fixed in 2.0.5 (at least on my system)
