### ISSUE TITLE
Kategorien synchronieren per CardDAV

### ISSUE THREAD

**Issue by ta7h12** [jobisoft/CategoryManager#19]
Wir nutzen einen owncloud 9.1-Server auf Ubuntu für unsere Kontakte. Meiner Beobachtung zufolge gibt es Probleme, wenn man bei einem Kontakt die Kategorie wegnimmt, ohne sonst was zu ändern. Der Upload zur owncloud funktioniert, aber der Download auf das andere Thunderbird erfolgt nicht. Kann das jemand bestätigen? Gibt's andere CardDAV-Addons? Abhilfe: als Kategorie was anderes eintragen, z.B. "keine", oder ein anderes Feld zusätzlich ändern.
Thunderbird 52.3.0, CategoyManager2 2.04, Inverse SOGo Connector 31.0.3

**Comment by jobisoft** [comment]
Och Mist, das ging mal. Ich schau es mir an.

**Comment by jobisoft** [comment]
Kann ich leider nicht reproduzieren.

TB 52.4.0
CatMan 2.04
Sogo Connector 31.0.5

Wie änderst du die Kategorien, um den Fehler zu triggern? Ich mache im CardDav-Adressbuch (nicht im globalen!) einen Rechtsklick auf einen Kontakt und ändere über das Kontext-Menu die Kategorie. Warte 10 Sekunden. Schließe Thunderbird. Öffne Thunderbird auf anderer Maschine. Thunderbird zeigt direkt an, dass ein Kontakt heruntergeladen wurde. Im Addressbuch Kontrolle: Geänderte Kategorie wurde übernommen.

VG
John
