### ISSUE TITLE
UTF-8 Or Accent export issue

### ISSUE THREAD

**Issue by bzels123** [jobisoft/CategoryManager#21]
Hello,
I try to export my list of contacts with "Category" columns, this works fine but some contacts or lines has weird typo such as  : 

- **affichÃ©** instead of **affiché**
- **ChristÃ¨le** instead of **Christèle** 

Maybe it's because of not using UTF-8 encoding?
is there a way to avoid these weird typo and have all accent exported correctly?
Thank you in advance
Kind Regards,
B.

**Comment by jobisoft** [comment]
Ae you using the export function of CategoryManager itself?

![image](https://user-images.githubusercontent.com/5830621/40779988-3f43dc52-64d7-11e8-91ed-135f725525d1.png)

I think it supports UTF8

![image](https://user-images.githubusercontent.com/5830621/40780033-67fe940c-64d7-11e8-9650-160acfa51d22.png)

**Comment by bzels123** [comment]
Hello 
I answer myself :
At stage : Export settings for CSV files
for **character set :** 
Instead of selecting **UTF-8** you need to select **Windows-1252 (ANSI)**
Then accents are correctly handled
Best Regards,
B.

**Comment by bzels123** [comment]
Hello,
I answer myself
you need to select "windows-1252 (ANSI)" instead of "UTF-8" at Export settings for CSV file stage.
and accents are correct

Kind Regards,
B.

**Comment by jobisoft** [comment]
Just to clarify: This is not a general answer. It depends on the application you use to read the exported file! Apparently your application only supports windows 1252. 

For most of the other users, UTF 8 (the defacto standard now) will probably work just fine.
