### ISSUE TITLE
Is it possible to send the changes made locally to the server?

### ISSUE THREAD

**Issue by MrcLpz** [jobisoft/CategoryManager#22]
If I made some changes in category locally I can´t see them in server. Is this functionallity built? I don´t see the "sync" button like in TBSync Addon.

**Comment by jobisoft** [comment]
The CategoryManager does not know anything about syncing, it just manages the categories. The "category" is just a contact property  like "email adress" or "name". If you change any property in a contact it is only changed locally.

If that contact belongs to a TbSync account/address book, you need to sync that account (via TbSync account manager) to get the changes to the server. 

However, most servers web interface do not display categories. Furthermore:
https://github.com/jobisoft/TbSync/wiki/Troubleshooting#outlookcom 

If you are not using outlook.com, you can make sure, that categories are synced by:

1. Add/Change a category via CategoryManager in the Thunderbird address book
2. Sync via TbSync account manager
3. Disable the account via TbSync account manager
4. Re-Enable the account via TbSync account manager
5. Check in the Thunderbird Addressbook, if the category is "still there"

**Comment by jobisoft** [comment]
Can i close this?

**Comment by MrcLpz** [comment]
Yes. I'm sorry.


En 10 de julio de 2018 8:43:02 John Bieling <notifications@github.com> escribió:

Can i close this?

**Comment by jobisoft** [comment]
No need to be sorry :-) i just wanted to know, if my answer solved your problem. Feel free to ask more questions.
