### ISSUE TITLE
Beta release for 2.09

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/CategoryManager#24]
Even though this file is a zip, you can install it as if it was an XPI file (cannot upload XPI files here).

[CatMan-beta.zip](https://github.com/jobisoft/CategoryManager/files/2663008/CatMan-beta.zip)

**Comment by jobisoft** [comment]
Will send this to Thunderbird review in 2-3 days.

**Comment by sinya13** [comment]
![catman_err_1](https://user-images.githubusercontent.com/4994987/49861667-770a6500-fe0d-11e8-9b58-01cbfd70ec62.jpg)

Marked area in not translated. But such an inscription is not present in the language files.

**Comment by jobisoft** [comment]
That description is stored directly on addons.thunderbird.net and must be changed there. Can you provide the translations, so I can copy paste them, after the new version has passed review?

Thanks,
John

**Comment by sinya13** [comment]
For CategoryManager (ru):

Это дополнение сканирует все карточки контактов выбранной в данный момент адресной книги, извлекает все категории и отображает их список внутри в адресной книге Thunderbird. Это позволяет переименовывать и удалять категорию (изменяет строку категории во всех карточках ее контактов членов).

**Comment by sinya13** [comment]
Similar for TbSync (ru):

Поддерживает через Exchange ActiveSync:
- Freenet
- Hotmail
- Kopano
- Office 365
- Outlook.com
- Strato
- другие серверы, которые поддерживают Exchange ActiveSync (EAS) v2.5 или v14.0

Поддерживает через CalDAV & CardDAV:
- Fruux.com
- GMX.de
- mailbox.org
- Nextcloud
- ownCloud
- SOGo
- другие sabre/dav-совместимые серверы

**Comment by sinya13** [comment]
Similar for DAV-4-TbSync (ru):

Поддерживает:
- GMX.de
- Fruux.com
- mailbox.org
- SOGo сервер
- ownCloud, Nextcloud и другие совместимые с sabre/dav серверы.

**Comment by sinya13** [comment]
Similar for EAS-4-TbSync (ru):

EAS-4-TbSync работает со следующими провайдерами EAS:
- Outlook.com
- Office 365
- Hotmail
- Freenet Sync
- Sync + (Deutsche Telekom)
- Strato Webmail Premium
- Amazon WorkMail с использованием ActiveSync v2.5
- mailbox.org

Кроме того, EAS-4-TbSync работает со следующими серверными системами (типа EAS v2.5 и v14.0):
- Microsoft Exchange
- SOGo
- Kopano (Zarafa)
- Horde
- Sonicle WebTop
- Tine 2.0
- Kerio
- Zoho (EAS 2.5)

**Comment by jobisoft** [comment]
CatMan is reviewed and online...

**Comment by jobisoft** [comment]
All translations are online, might take a while, until they and up inside Thunderbird.

**Comment by jobisoft** [comment]
As v2.09 is officially released, I close this.
