### ISSUE TITLE
Synch contacts with EAS?

### ISSUE THREAD

**Issue by Ozwingle** [jobisoft/CategoryManager#25]
I am new to TB, migrating from Outlook. I have connected to Outlook for email and contacts. Thank you for TBsync and EAS Provider. I have installed CategoryManager and restarted and resynched with EAS outlook account. The categories that do exist for many contacts on Outlook EAS are not showing up in TB address book or Cardbook.  

What can I do to have TBsync and CategoryManager read and synchronize the categories in my Outlook contacts?
Thank You

**Comment by jobisoft** [comment]
Sorry:

https://github.com/jobisoft/EAS-4-TbSync/wiki/General-troubleshooting#outlookcom
