### ISSUE TITLE
CategoryManager in die Sidebar des Nachrichtenfensters integrieren

### ISSUE THREAD

**Issue by xhosch** [jobisoft/CategoryManager#28]
Hallo und schönen guten Tag, der CategoryManager ist mir immer wieder hilfreich. Leider ist er stets nur funktionell, wenn man eine E-Mail **_neu_** verfassen will. Soblad es jedoch darum geht eine E-Mail an bestimmte oder alle Mitglieder einer Kategorie **_weiterzuleiten_**, fehlt mir der CategoryManager in der Sidebar. Gibt es eine Möglichkeit den Manager in die Sidebar des Nachrichtenfensters (nach dem Klick auf "E-Mail-Verfassen" bzw. "E-Mail-Weiterleiten") zu integrieren? Ich hoffe mich verständlich ausgedrückt zu haben.

Herzlichen Dank für diesen Manager.
Grüße Holger

**Comment by jobisoft** [comment]
Wenn sie die Sidebar mit F9 im "Nachrichten verfassen" Fenster aktivieren, sollte unter dem Adressbuch-Selektor ein Kategorie Selektor sein:

![image](https://user-images.githubusercontent.com/5830621/57285876-715f3580-70b4-11e9-9777-a9c511baf081.png)

Wenn Sie eine Kategorie auswählen, werden alle Mitglieder ausgewählt, sodass sie dann nur noch auf einen der drei Hinzufügen-Knöpfe drücken müssen.

Können Sie das bestätigen?

**Comment by xhosch** [comment]
Hallo und vielen Dank für Ihre schnelle Rückmeldung. Dann ist die Anzeige der Kategorien des CategoryManagers in die Sidebar bei "E-Mail-Verfassen/Weiterleiten" bereits integriert. Das war mir nicht bekannt. Die Kategorien des CategoryManagers in der Sidebar wurden und werden mir bisher nicht angezeigt.
Ich nutze LinuxMint 19.01 mit Thunderbird 60.6.1 und dem CategoryManager 2.09. Siehe Abbildung:
![Thunderbird Sidebar ohne Kategorien](https://user-images.githubusercontent.com/50357925/57291642-19c6c700-70c0-11e9-95c3-bcfdfb010da1.png)
Der "Kategorie-Filter" gehört, so meine ich, nicht dem CategoryManager an.
Begehe ich vielleicht einen Anwendungsfehler?
Hier nachfolgend mal meine aktivierten AddOn's
![Thunderbird aktivierte AddOn's](https://user-images.githubusercontent.com/50357925/57292529-3237e100-70c2-11e9-9bfc-107d3d618e62.png)

**Comment by jobisoft** [comment]
Doch, der Kategorie-Filter ist von mir. Wenn du den CategoryManager deaktivierts, dann ist er weg.

In diesem Kategorie-Filter werden alle Kategorien des ausgewählten Adressbuchs aufgelistet (über den Selektor oben drüber). Es ist genau das was du suchts. 

Außer es gibt unter Linux einen bug. Dann bräuchte ich Screenshoots von den Kategorieauflistungen im Adressbuch und in der Sidebar, wo der Unterschied sichtbar wird.

**Comment by xhosch** [comment]
Vielleicht sprechen wir nicht von dem gleichen "Kategorie-Filter"? Bei daktiviertem CategoryManager bleibt der Kategorie-Filter den ich meine, sichtbar.
Nachstehend zeigen die Abbildungen folgendes:
Bild 01 - aktivierter CategoryManager
Bild 02 - aktivierter CategoryManger
Bild 03 - aktivierter CategoryManager
Bild 04 - deaktivierter CategoryManager
Bild 05 - deaktivierter CategoryManager
Bild 06 - deaktivierter CategoryManager
Bild 07 - deaktivierter CategoryManager
![Bild 01 - aktivierter CategoryManager](https://user-images.githubusercontent.com/50357925/57311947-e8b0bb80-70ec-11e9-8c7d-7a1ffa02b044.png)
![Bild 02 - aktivierter CategoryManger](https://user-images.githubusercontent.com/50357925/57311948-e8b0bb80-70ec-11e9-8299-6f44f34df083.png)
![Bild 03 - aktivierter CategoryManager](https://user-images.githubusercontent.com/50357925/57311949-e8b0bb80-70ec-11e9-8b23-29ccd2a61769.png)
![Bild 04 - deaktivierter CategoryManager](https://user-images.githubusercontent.com/50357925/57311950-e8b0bb80-70ec-11e9-9e8c-d540c7d40912.png)
![Bild 05 - deaktivierter CategoryManager](https://user-images.githubusercontent.com/50357925/57311951-e9495200-70ec-11e9-97b1-58d8907e522a.png)
![Bild 06 - deaktivierter CategoryManager](https://user-images.githubusercontent.com/50357925/57311953-e9495200-70ec-11e9-9126-7cd601f713e0.png)
![Bild 07 deaktivierter CategoryManager](https://user-images.githubusercontent.com/50357925/57311955-e9495200-70ec-11e9-99dd-525fd3cf1495.png)

**Comment by jobisoft** [comment]
Was ist denn da kaputt? Also das hier ist der Filter, der von CatMan hinzugefügt wird:

![image](https://user-images.githubusercontent.com/5830621/57313735-7e017f00-70f0-11e9-96fc-34fb19d1cfba.png)

Der code dazu ist [hier](https://github.com/jobisoft/CategoryManager/blob/master/sendtocategory/content/contactpanel/abContactsPanel_overlay.xul#L18-L25).

Du siehst meinen Filter tatsächlich nicht. Ich vermute, ein anderes Add-On funkt dazwischen (aber warum sollte das meinen Filter komplett verstecken? *grübel*). Um das zu bestätigen, müsstest du mal alle Add-Ons bis auf den Category Manager deaktivieren und gucken was passiert.

**Comment by xhosch** [comment]
So, es hat am CardBook-AddOn gelegen. Ich habe es deaktiviert / entfernt. Nun wird der CategoryManager auch in der Sidebar im Fenster "E-Mail-Verfassen/Weiterleiten" angezeigt. Ich habe das CardBook-Add-On ohnehin nicht genutzt. Vielen Dank für den schnellen Support.
Grüße
Holger
![CardBook-AddOn](https://user-images.githubusercontent.com/50357925/57315779-95426b80-70f4-11e9-96f1-e3a3ad447c0a.png)

**Comment by jobisoft** [comment]
Ok, danke für die Info. Falls du doch CardDAV support benötigst, kannst du ja TbSync nehmen :-)
