### ISSUE TITLE
Categories not being recognised within mailing lists

### ISSUE THREAD

**Issue by sekdiy** [jobisoft/CategoryManager#3]
It seems that categories are not recognised within mailing lists, even though they are correctly listed in the adress book view.

Opening the contacts' edit view from within the mailing list reveals that categories are still set correctly.

Fig.1: CategoryManager correctly recognises the categories from contacts.
![screen shot 2015-12-17 at 15 23 16](https://cloud.githubusercontent.com/assets/2700095/11871848/66e86f1a-a4d2-11e5-82b6-5d712c254c1b.png)

Fig.2: In a mailing list categories are not displayed, even though they are still set.
![screen shot 2015-12-17 at 15 23 58](https://cloud.githubusercontent.com/assets/2700095/11871849/66e8b2b8-a4d2-11e5-918c-ea6417b5f734.png)

Windows 7 / 2012 R2 (x64), Thunderbird 38.4.0, CategoryManager 1.60, SOGo Connector 31.0.2, ownCloud 8.2.1

**Comment by jobisoft** [comment]
Das ist nicht unterstützt und wird es (von mir) wohl auch nicht. Die Idee ist ja gerade die Thunderbird Mailinglisten durch die kategoriebasierten Kontaktgruppen zu ersetzen.

Die Thunderbird Mailinglisten sind (nach meinem Kentnissstand) einfach nur lokal abgespeicherte Listen von Email-Adressen. Änderst du die Emailadresse von "Erstkontakt" im Adressbuch, ändert sich nicht die entsprechende Emailadresse in der Mailingliste. Außerdem werden die Thunderbird Mailinglisten nicht über CardDAV gesynct.

Könntest du mir ein Anwendungsszenario geben, wo die kategoriebasierten Kontaktgruppen die Thunderbird Mailinglisten nicht ausreichend ersetzt?

**Comment by sekdiy** [comment]
> Änderst du die Emailadresse von "Erstkontakt" im Adressbuch, ändert sich nicht die entsprechende Emailadresse in der Mailingliste.

Doch doch, sogar in beide Richtungen (TB 38.5.0 für Mac OS X)!

> Außerdem werden die Thunderbird Mailinglisten nicht über CardDAV gesynct.

Das ist richtig, allerdings beziehe ich mich tatsächlich nur auf die Kategorien innerhalb der Mailinglisten, nicht auf das Synchronisationsverhalten von TB oder CategoryManager/SoGo.

> Könntest du mir ein Anwendungsszenario geben, wo die kategoriebasierten Kontaktgruppen die Thunderbird Mailinglisten nicht ausreichend ersetzt?

Das war gar nicht der Inhalt meines Tickets. ;)

Vielmehr ergänzen sich (synchronisierte) Kategorien und (lokal gespeicherte) Mailinglisten sehr gut, wenn man anwendungsbezogen eine Mailingliste anhand von Kategorien zusammenstellt.

Vielleicht ein theoretisches Szenario: Kategorien stellen ein Filter für mögliche Adressaten eines Rundschreibens dar. Tatsächlich soll das Rundschreiben aber nur an eine Teilmenge bzw. Schnittmenge einer bzw. mehrerer Kategorien adressiert werden. Ich lege also eine Mailingliste anhand der Kategorien an, bearbeite diese aber noch einmal vor dem Versand des Rundschreibens. Dafür weise ich weder eine neue Kategorie zu, noch ändere ich die bestehenden (weil das semantisch etwas völlig anderes wäre). Anschließend kann die Mailingliste gelöscht werden - oder zumindest muss sie nicht synchronisiert werden - da es dasselbe Rundschreiben so nie wieder geben wird.

Die mit den Kontakten gespeicherten Kategorien werden jedoch nicht angezeigt, falls man die Kontakte innerhalb einer Mailingliste betrachtet. Ich hielt das für einen möglichen Bug im CategoryManager, glaube Dir aber auch, wenn Du sagst, dass das einfach ein fehlendes Feature von TB ist.

**Comment by jobisoft** [comment]
Oh, schön das TB inzwischen die Adressänderungen bei Kontakten in Mailinglisten auch auf die Kontakte in den Adressbüchern anwendet. Das wusste ich bis jetzt noch nicht.

Ich kann sehen, dass es u. U. hilfreich wäre, auch Mailinglisten nach Kategorien filtern zu können. Ich schreib es mal ganz unten auf meine ToDo Liste. Danke für die Meldung, ich hätte das nicht gefunden, weil ich grundsätzlich nicht mehr mit Mailinglisten arbeite und daher damit auch nicht teste.

**Comment by jobisoft** [comment]
Ich denke, es ist im aktuellen master branch teilweise gefixt. Kannst Du dir das mal anschauen? In der INSTALL.md steht, wie das geht.

Die Kontakte werden von Thunderbird jetzt tatsächlich - wie von dir bereits erwähnt - über Ihre ID in Listen eingehängt. Angenommen es gibt 20 Kontakte in Kategorie K1 und davon sind 10 Kontakte in Liste L1. Bin ich in der Liste L1 und benenne Kategorie K1 in K2 um, dann sind diese Kontakte dann auch im übergeordneten Adressbuch in Kategorie K2 (also 10 in K1 und die anderen 10 in K2).

D.h. Änderungen an den Kategorien von Kontakten in der Liste haben Auswirkungen auf Kategorien im übergeordneten Adressbuch. Logisch. Es ist ja der selbe Kontakt. Ist das wie erwartet?

Wie ist die Erwartung beim Direkt-Edit-Modus innerhalb einer Liste, besonders beim Hinzufügen von Kontakten/Email-Adressen, die es in der Liste noch nicht gibt, dafür aber im übergeordneten Adressbuch? Soll der Kontakt aus dem übergeordneten Adressbuch dann der Kategorie und gleichzeitig auch der Liste hinzugefügt werden, oder soll ein neuer Kontakt erstellt werden? Momentan sagt er zwar, Kontakt wird erstellt, tut aber nichts. Wie ist die Erwartung?

**Comment by sekdiy** [comment]
Ich konnte inzwischen testen mit TB 47.0 (beta, Windows 8) bzw. TB 45.2.0 (release, Mac OS X 10.11.5) und CategoryManager 1.62 bzw. SOGo Connector 31.0.2 (via Mozilla).

Die Zuordnung über die ID der Kontakte funktioniert tatsächlich. 
Ich kann innerhalb einer (nicht synchronisierten) Liste einen Kontakt bearbeiten, dort Kategorien ändern, den gespeicherten Kontakt synchronisieren und die Änderung wird repliziert.
Insofern ist das für mich wie erwartet, ja.

Im Direkt-Edit-Modus kann ich außerhalb einer Liste problemlos arbeiten.
~~Die Frage nach dem Direkt-Edit-Modus innerhalb einer Liste verstehe ich an dieser Stelle nicht.
Innerhalb einer Liste stehen Kategorien weiterhin nicht zur Verfügung (ursprüngliches Problem). Darüber hinaus ist es mir innerhalb von Listen auch nicht möglich, direkt neue Kategorien zu erstellen (siehe aktuelle Screenshots).~~

Die Erwartung ist hier gar nicht so leicht zu formulieren. Tatsächlich ist es ja eine mehrdeutige Handlung, innerhalb einer Liste zu einer Kategorie einen Kontakt hinzuzufügen, der weder in der Liste, noch in der Kategorie ist. 

Konsequent wäre es sicherlich, den Kontakt aus dem übergeordneten Adressbuch zu verknüpfen. Das entspräche auch der sonstigen Arbeitsweise der Listen.

Das Ergebnis wäre dann, dass der Kontakt die Kategorie erhält und zur Liste hinzugefügt wird (weil er nur so auch innerhalb der Liste unter der Kategorie angezeigt werden kann).
Anders formuliert: ich favorisiere die konsequente Verknüpfung der Vorkommen eines Datensatzes und spreche mich gegen neu erstellte Kontakte, Duplikate, etc. aus.

Edit: Ich habe mal schnell noch die Quellen direkt mit meinem TB-Profil verknüpft und so die Version 2.01 getestet. Innerhalb der Listen werden die Kategorien nun offenbar genau so behandelt wie innerhalb von echten Adressbüchern.

**Comment by jobisoft** [comment]
So, ich denke das Thema ist jetzt durch. Ich würde mich freuen, wenn Sie v2.01 mal testen könnten.

Beim bulk edit werden Kontakte jetzt nicht nur in der Liste sondern auch im übergeordneten Adressbuch gesucht. Wenn "neue" Kontakte dort gefunden werden, werden die Kontakte im übergeordneten Adressbuch der Kategorie hinzugefügt und dann auch in die Liste gelinkt. Sollte ein neuer Kontakt erstellt werden müssen, wird er im übergeordneten Adressbuch erstellt und dann ebenfalls in die Liste gelinkt.

**Comment by sekdiy** [comment]
Ich habe mir mal die v2.02 vorgenommen und _bulk edit_ ausprobiert.
Hat wie beschrieben funktioniert: ich konnte Kontakte aus dem übergeordneten Adressbuch heranziehen sowie neue Kontakte erzeugen lassen, die dann im übergeordneten Adressbuch landeten. 

Vielen Dank für den Support!
