### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by janzet** [jobisoft/CategoryManager#30]
Hello, is there a Dutch translation available for category manager?

**Comment by jobisoft** [comment]
No, but you can contribute on :-)

https://github.com/jobisoft/CategoryManager/tree/master/sendtocategory/locale

**Comment by janzet** [comment]
> No, but you can contribute on :-)
> 
> https://github.com/jobisoft/CategoryManager/tree/master/sendtocategory/locale

I will try

**Comment by janzet** [comment]
I'll try

**Comment by jobisoft** [comment]
from this list, the code for dutch is simply "nl", isn't it?
https://searchfox.org/comm-central/source/mail/locales/all-locales

**Comment by janzet** [comment]
Yes that's right

**Comment by janzet** [comment]
How do I create the map nl in CategoryManager/sendtocategory/locale/ ? In that map I'l have to put the files 'bundle.strings' , 'catman.dtd' and 'import-export-wizard.dtd' is'nt it?

**Comment by jobisoft** [comment]
You first fork this repository which gives you a copy in your own account. You than modify your own copy (create a nl folder in the locales folder and put the files there). When you are done, create a pull request - github will guide you.

**Comment by jobisoft** [comment]
If you need further assistance, just ping me!

**Comment by jobisoft** [comment]
I forgot one detail: To actually see you translation in action, you also must add an entry here:
https://github.com/janzet/CategoryManager/blob/master/sendtocategory/chrome.manifest

Something like

```
locale sendtocategory nl locale/nl/
```

And to use your custom version of quicktext, you need to zip the "sendtocategory" folder and manually install that in the AddOn Manager of TB68 via the gear menu in the upper right corner.

**Comment by janzet** [comment]
I have the translation finished and now when I create a pull request there is the message "There aren’t any open pull requests." I don't know how it works. Can you help me?

**Comment by jobisoft** [comment]
You need to push this button:

![image](https://user-images.githubusercontent.com/5830621/64492882-63dfd500-d279-11e9-9818-764b361e8fc2.png)

If you struggle, I can do it for you. But just give it a try ...

**Comment by janzet** [comment]
I think it's installed now. When I try to install it on my laptop there is a message that says it is not compatable with thunderbird 60.90.0
What can I do?

**Comment by jobisoft** [comment]
You patched the master branch, which is compatible with Thunderbird 68 only. To test it, you have to download and install Thunderbird 68, which is the current official version of Thunderbird.

https://www.thunderbird.net/

**Comment by janzet** [comment]
On tweakers.net I see: Thunderbird version 68.0 is only offered as direct download from thunderbird.net and not as upgrade from Thunderbird version 60 or earlier. A future version 68.1 will provide updates from earlier versions.
I have 8 email adresses and about 100 local maps so I'm afraid to install it now. I think I better can wait till 68.1? What do you think?

**Comment by jobisoft** [comment]
You can of course wait until you receive the update to TB 68.1

The reason we do not ship TB 68.0 as an update to all TB 60.x users: We want to catch and fix bugs which have been missed during the beta phase, before we roll out TB 68 to the world. But so far no fatal bugs have emerged. 

Nevertheless, you could create the Pull Request, so I can have a look already. Do you need further assistance for that?
