### ISSUE TITLE
Remove redundant link “Support site” from https://addons.thunderbird.net/en-US/thunderbird/addon/categorymanager/

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/CategoryManager#33]
On the right of https://addons.thunderbird.net/en-US/thunderbird/addon/categorymanager/ are two links:

Add-on home page →https://github.com/jobisoft/CategoryManager
Support site → https://github.com/jobisoft/CategoryManager

Remove one of the links, as there is no point to have both.

Likewise for https://addons.thunderbird.net/en-US/thunderbird/addon/dav-4-tbsync/, where the difference is minimal

**Comment by jobisoft** [comment]
There was a hiccup. The issue page should be used for support. With TbSync and friends I changed the support page to the wiki.
