### ISSUE TITLE
Import function and Enigmail

### ISSUE THREAD

**Issue by KarstenSteinke** [jobisoft/CategoryManager#35]
Hello,

I have just tried the good looking CategoryManager in Thunderbider 68.1.1 (Opensuse) but have two problems:

1. Is it possible to import the "categories" from MoreFunctionsForAddressbook? I have some thousands of addresses and to do it manually is .... 
2. When I try to send an email to a category, there seems to be a problem with Enigmail, used for the encription in one of my email accounts. The email creation is called, a message "start Enigmail" appears and that's it. Enigmail in normal usage works fine.

Any idea/ help, what I can do?

Thank you

Karsten

**Comment by jobisoft** [comment]
CategoryManager does have a MFFAB mode, where you can switch between CategoryManager Categories and MFFAB Categories (or convert between the two). 

![grafik](https://user-images.githubusercontent.com/5830621/69979584-e0a7e580-152e-11ea-8721-54b0ce355f56.png)

The problem: MFFAB must be installed, but I think MFFAB does not work with TB68 :-(

You can trick CategoryManager into believing MFFAB is installed by manually creating the following preference in the advanced Thunderbird options:

`morecols.category.separator`

and specify the seperator used (I do not remember what MFFAB actually used). You can use the export function from the category manager to export your contacts and than look at the "Category" field and identify the seperator.

I have no idea what is wrong with Enigmail. Lets tackle that later.

**Comment by jobisoft** [comment]
I looked at the old code of MFFAB and the standard separator is just a comma, so you nee to add the following preference to Thunderbird:


![grafik](https://user-images.githubusercontent.com/5830621/70084179-22f42400-160e-11ea-87fb-f824c4a24b8a.png)

![grafik](https://user-images.githubusercontent.com/5830621/70084232-3b643e80-160e-11ea-9822-225ca6b3083c.png)

![grafik](https://user-images.githubusercontent.com/5830621/70084277-4c14b480-160e-11ea-87f3-7b78c9a3a3aa.png)

**Comment by KarstenSteinke** [comment]
Thank you very much. I'll try this :-)
