### ISSUE TITLE
Exporting all contacts to .csv 

### ISSUE THREAD

**Issue by chedman6** [jobisoft/CategoryManager#36]
I have just exported my full contacts list to a csv file but it doe not populate the categories field. I am sure it used to when I last did it about a year ago!

David Elliott

**Comment by jobisoft** [comment]
Confirmed! Thanks for reporting this. Seems to have gone missing with the TB68 update. Working on it.

**Comment by jobisoft** [comment]
Can you check, if it is fixed in this version:
[CatMan-beta.xpi](https://github.com/jobisoft/CategoryManager/files/3929585/CatMan-beta.zip)

You must first uninstall your current CatMan, restart Thunderbird, close the AddOn Manager, reopen the AddOn Manager, install CatMan from file.

**Comment by jobisoft** [comment]
@chedman6 : Does it work for you now?

**Comment by chedman6** [comment]
Yes, it works fine. Thanks very much. 

⁣Sent from my Galaxy phone.
​
