### ISSUE TITLE
Conflict between CategoryManager and Thunderbird Conversations

### ISSUE THREAD

**Issue by laspic** [jobisoft/CategoryManager#37]
Following [this issue](https://github.com/protz/thunderbird-conversations/issues/1402), I post here about a conflict between CategoryManager and [Thunderbird Conversations](https://github.com/protz/thunderbird-conversations). We suspect a problem in the way CategoryManager attempts to load its category tools.

- **Thunderbird version:** 68.2.2
- **CategoryManager version:** 3.7
- **Thunderbird Conversation version:** 2.15.16
- **Operating System:** Xubuntu 18.04

**What did you do?**
I try to open an existing contact card directly from the small popup on the name of a participant of a conversation, in clicking on the pencil button, provided by Thunderbird Conversations add-on.

**What did you expect to happen?**
I expect the contact card to open and display all data recorded for the target contact. I also expect to be able to add some modifications to that contact card.

**What actually happened?**
The contact card open and display not all data recorded for the target contact but only some of them, namely email address and phone number. The name and surname, photo field are particularly empty. Sometimes the contact card is totally virgin. All modifications are always lost.

When opening the contact card, the following message displays in the Error Console : `TypeError: jbCatMan.getReducedCategoriesForHierarchyMode is not a functioncommon-card-overlay.js:201:36`

**How to workaround ?**
Disabling the CategoryManager add-on is sufficient to solve the problem. Everything works fine if Thunderbird Conversations runs alone.

**Comment by jobisoft** [comment]
Can you retry with current release 3.9 (released just now)?

**Comment by laspic** [comment]
Thank you very much. Everything works much better! :)

However, there is still a little thing to adjust: when opening the contact card from Thunderbird Conversation Button, the tab "Categories" is totally blank (the existing categories are not displayed). When opening it in the standard way, everything works perfectly.

**Comment by jobisoft** [comment]
Thanks, please do not save/modify any of your contacts in this dialog, as you will actually clear your categories. Working on a fix.

**Comment by jobisoft** [comment]
I just released v3.10, which should fix this. Can you confirm?

**Comment by laspic** [comment]
v3.10 fix the issue for existing contacts, but not for new ones. In other words, when i create a new contact card with the Thunderbird Contact button, the tab "Categories" is still blank.

Note that even when creating a new contact in the standard way, it is not perfect. Here also the tab "categories" is blank at first; the categories appears only after selecting another address book, and going back to the first one.

**Comment by jobisoft** [comment]
I think that is conceptional. If you select a specific address book, only the categories avail in that adressbook are shown. If you select the global one, all categories of all addresbooks are shown (to be selected).

That should be the same for the standard address book or the Conversations button. I do not know, what addressbook the conversations button is "using".

Is that what you are seeing?

**Comment by jobisoft** [comment]
Hm, no, that is indeed broken.

**Comment by jobisoft** [comment]
Before I release this and you find another bug, this is a pre release for you to test beforehand :-)
[CatMan-beta.xpi](https://github.com/jobisoft/CategoryManager/files/4083739/CatMan-beta.xpi.zip)


You must uninstall your current version of the CategoryManager, restart Thunderbird and then install this pre release. Simply installing the pre release over your current version will not work (bug in TB).

**Comment by laspic** [comment]
I haven't found any other bugs on v3.10.1 so far! From my (humble) point of view, you can release it.

Thanks for all!

**Comment by jobisoft** [comment]
Will be released soon as 3.11.
