### ISSUE TITLE
Google contact groups won't work

### ISSUE THREAD

**Issue by anatolytkach** [jobisoft/CategoryManager#38]
I've synced with Google Contacts using TBSync add-on while having CategoryManager already installed.
Unfortunately, after syncing I don't see any Google contact groups show up in my TB address book — just see all contacts as Uncategorised. Any idea?

**Comment by jobisoft** [comment]
Google is not announcing them via CardDAV. You can enable debug logging in the TbSync Account Manager and disable and then re-enable your google addressbook, to see what information is presented by google. 

It is a PITA but nothing I can do. They decided to not fully implement the CardDAV standard.

**Comment by anatolytkach** [comment]
Got it (ᓀ︵ᓂ)
Thanks a lot for your feedback anyway!
BTW, I used to use the gContactSync before, which was able to get all groups from G to the TB AB.
Unfortunately, gContactSync won't connect to G anymore. Do you have any idea about a workaround to get the G groups in TB.

**Comment by jobisoft** [comment]
gContactSync is using a specific Google API not compatible with anything else. There may come a google provider for TbSync someday, using that API as well, but currently no plans.

The workaround would be to switch to a different company, which is not selling your data :-) like fruux.com.

**Comment by anatolytkach** [comment]
I see, the bigG is sucks..(ᓀ︵ᓂ)
Thank you for the fruux, will take a look.
