### ISSUE TITLE
gmail lables

### ISSUE THREAD

**Issue by JohnIIT** [jobisoft/CategoryManager#39]
Hi. I installed TBSync, Provider, and Category Manager. My contacts are syncing correctly, but categories (gmail calls them Labels) are no syncing.

My gmail is my university's gsuite, with @iit.edu as the domain.

Am I doing something wrong?

Thanks.

**Comment by jobisoft** [comment]
Sadly not supported. Google does not send them via CardDAV. Nothing I can do.

**Comment by JohnIIT** [comment]
Thanks for letting me know. Great extension.
