### ISSUE TITLE
Not able to export contents of category

### ISSUE THREAD

**Issue by alexanderhaensch** [jobisoft/CategoryManager#4]
There is no visible way to export a category to a csv or tsv file. 
This could be helpful to manage large addressbooks.
Is there a way to export an addressbook with the categories field included?

**Comment by jobisoft** [comment]
Usually export is done via the CardDAV Backend (for example the web login of your own cloud server). This export will include the CATEGORIES field.

This export can than be imported to other CardDAV servers. If you want to import into outlook, or want to filter/reduce the addressbook to some categories, the script here helped me a lot: http://sourceforge.net/projects/bulkvcftocsv/: It convertes the VCF file to Excel, where you can search/filter entries.

What is your use case in detail?

**Comment by alexanderhaensch** [comment]
@jobisoft Thanks for the pointer. I will definitively look into that tool.
Actually i would like to get a list of addresses as csv for one category. For example for sending physical mail to a category.

I think it would be possible to hook that below 'send email to category'
![snapshot4](https://cloud.githubusercontent.com/assets/1120164/13456450/84875744-e063-11e5-9f4a-a03e777ee88b.png)

What do you think?

**Comment by jobisoft** [comment]
Hi,

the categorymanager does have a feature for "get all emails of a 
category", it is called the "direct edit mode".

Click with your right mouse button on a category on the category pane 
and you will get a context menu, one entry is called "direct edit mode" 
or something, it will open a list with all email adresses part of that 
category. You can just copy them from there. You can also use this mode 
to add a bunch of addresses to a category.

Does that help?

Yours,
John

Am 02.03.2016 um 10:44 schrieb alexanderhaensch:

**Comment by jobisoft** [comment]
Can I close this?

**Comment by alexanderhaensch** [comment]
This functionality is partly exposed by the thunderbird extension cardbook https://addons.mozilla.org/de/thunderbird/addon/cardbook/ . The context menu there has much more possibilities.
closing.

**Comment by jobisoft** [comment]
Because I had a situation, where I need that function by myself, I will implement it in the next release (1.62 or 1.63)

**Comment by alexanderhaensch** [comment]
If you have a version, i am willin to test that.

**Comment by jobisoft** [comment]
Are you still using the CategoryManager? Version 2.03 includes now an import/export wizard. I would appreciate your feedback. Currently only CSV is working, VCF is planned for (much) later.

Version 2.03 is is not yet available from Mozilla, you have to get it from the master branch of this repo. It does not yet have an english translation, only german.

Instructions on how to use the latest version from the repo can be found here:
https://github.com/jobisoft/CategoryManager/blob/master/INSTALL.md

**Comment by Coernel82** [comment]
No, not using it any more as CardBook has Categories and CardDav in one
- so for my purposes much better.

Am 30.09.2016 um 11:22 schrieb John Bieling:
