### ISSUE TITLE
default color bug with dark window default theme

### ISSUE THREAD

**Issue by Neonunux** [jobisoft/CategoryManager#44]
Default dark theme in window [setting](https://geekermag.com/wp-content/uploads/2018/05/windows-10-dark-mode-1024x596.png) displays a white theme 

![category_manager_bug](https://user-images.githubusercontent.com/2800474/76648692-71935180-655f-11ea-84f1-7b111fd1bb1f.png)

**Comment by jobisoft** [comment]
I have no idea how themes work. I set the background of that listbox to white. If someone knows how to use themes placeholder instead of real colors, ping me.

**Comment by Neonunux** [comment]
well.. i didn't find anything in docs.. 

That's interesting because i have the same bug in lighning on linux.. 

I'm going to dive in the devtools to find how it's working..

**Comment by Neonunux** [comment]
It seems to be necessary to use a bunch of CSS variables such as :
```
--panel-disabled-color
--lwt-accent-color
--lwt-text-color
--arrowpanel-background
--arrowpanel-color
--arrowpanel-border-color
--lwt-toolbar-field-background-color
--lwt-toolbar-field-color
--lwt-toolbar-field-border-color
--tab-line-color
--toolbar-bgcolor
--urlbar-separator-color
--chrome-content-separator-color
--lwt-toolbarbutton-icon-fill
--autocomplete-popup-background
--autocomplete-popup-color
--autocomplete-popup-border-color
--sidebar-background-color
--sidebar-text-color
```
instead of arbitrary one like 
https://github.com/jobisoft/CategoryManager/blob/eca821490acecbc665be937506407d38df97c7df/sendtocategory/skin/richlist-cardedit.css#L2
or 
https://github.com/jobisoft/CategoryManager/blob/eca821490acecbc665be937506407d38df97c7df/sendtocategory/skin/richlist.css#L39

by remplacing `--custom-color` by `--sidebar-background-color` for example.

I guess it must be these variables are redefined in a theme.

Unfortunately I don't have the code on hand to make a patch but it seems to work according to my tests in the developer tools by switching from one theme to another

**Comment by jobisoft** [comment]
Version v6.2 adheres to the selected theme.
https://github.com/jobisoft/CategoryManager/releases/tag/v6.2
