### ISSUE TITLE
Support for Polish letters

### ISSUE THREAD

**Issue by slawszar** [jobisoft/CategoryManager#45]
When you include Polish letters in the category name, the category list (window left bottom, "Filter contacts by categories:") breaks by category that includes a Polish letter = stops listing categories.
Polish letters: ąćęłńóśżźĄĆĘŁŃÓŚŻŹ
ą \u0105
ć \u0107
ę \u0119
ł \u0142
ń \u0144
ó \u00F3
ś \u015B
ź \u017A
ż \u017C
Ą \u0104
Ć \u0106
Ę \u0118
Ł \u0141
Ń \u0143
Ó \u00D3
Ś \u015A
Ź \u0179
Ż \u017B

**Comment by linusboyle** [comment]
I can confirm this on CJK characters. Seems unicode characters are not well supported

**Comment by avlubimov** [comment]
yes, cyrillic characters in category name not work too.

**Comment by jobisoft** [comment]
Looks like this has been fixed in v6.2?
https://github.com/jobisoft/CategoryManager/releases/tag/v6.2
