### ISSUE TITLE
Sender Address via Category

### ISSUE THREAD

**Issue by Reichenwallner** [jobisoft/CategoryManager#46]
Dear Sirs and Madams,

using the CategoryManager is quite nice especially if you have to send e-mails to a bunch of addresses and have to ensure data-protection.

One thing I for myself observe a bit "bothersome".
I have more than one address books: Private, work, ...
When I use CategoryManager to send an email to a Kategory, e.g. "colleagues" which are saved in "work" address book they are put to BCC which is fine, but in my sender address my private email is used and not the one for work. It can be corrected by klicking and choosing the right one, but sometimes you can forget that correction (especially when you are in a hurry). 
Would there be a solution for that beside manually correcting? Maybe a connetion of a default own addresses to the address book or category (which can be changed manually as now - but the first appearance is set)

I would be grateful for your information.
Yours sincerely
M. Reichenwallner

**Comment by jobisoft** [comment]
This should do the trick:
https://addons.thunderbird.net/addon/identity-chooser/
