### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by slawszar** [jobisoft/CategoryManager#47]
PL translation attached: 
[pl-PL.messages.json.txt](https://github.com/jobisoft/CategoryManager/files/4671400/pl-PL.messages.json.txt)
I failed to test it, due to the fact that the _locale and locale folders in the categorymanager-3.11-tb.xpi file contain language files in converted form.

**Comment by jobisoft** [comment]
That is the new format for TB78. I will include the PL translation.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/CategoryManager/commit/7b5ff6ead3d7ef6a71b443b92caeb7cc1973a6f7
