### ISSUE TITLE
Show Categories for Google Contacts using Browser & Category changes not reflecting in another PC after syncing in first PC & followed by second PC

### ISSUE THREAD

**Issue by johnaaronrose** [jobisoft/CategoryManager#48]
I've just started using tbsync, Provider for Caldav & Category manager on my gmail account. I can set the categories for various contacts using T'bird. I then sync Address Book etc in tbsync which goes Ok. However, I am not able to see the Categories for those Contacts displayed in Google Contacts looked at from my Browser. Also, when I sync Address Book from another computer, the Categories are not applied to those Contacts even though any new contacts or other changes to existing contacts are. Any ideas about how to show Categories for Contacts displayed  in Google Contacts and how to make tbsync cause updates to Categories from T'bird to Contacts displayed in Google Contacts?

**Comment by jobisoft** [comment]
https://github.com/jobisoft/CategoryManager/issues/38
