### ISSUE TITLE
Why is existing field Label not used rather than new field Category

### ISSUE THREAD

**Issue by johnaaronrose** [jobisoft/CategoryManager#49]
I've just started using tbsync, Provider for Caldav & Category manager on my gmail account. I can set the categories for various contacts using T'bird. I then sync Address Book etc in tbsync which goes Ok. However, I am not able to see the Categories for those Contacts displayed in Google Contacts looked at from my Browser, because Category is a new field to Google. So on each computer that I use on my home network, I have to create a Category & assign Contacts to it again. Consider a company with a lot of computers: this would entail a lot of work t o assign Contacts to a Category. 
I suggest using the existing Label field for Contacts to create a 'list'/'group' of Contacts.

**Comment by jobisoft** [comment]
This is identical to your last issue, which I closed a few hours ago. Can you please read the issue I referred to in the closing message?

If you still have questions after that feel free to ask for details.

Summary: Google sucks.

**Comment by johnaaronrose** [comment]
I did read your reply to my last issue. This is different in that I am suggesting a solution to the problem caused by having a new field of Category: i.e. use an existing field Label.

**Comment by jobisoft** [comment]
Google does not allow access to that groups field via CardDAV. If possible, I would have used that, of course.
