### ISSUE TITLE
unable to get CM to work

### ISSUE THREAD

**Issue by DPS304** [jobisoft/CategoryManager#50]
I'm attempting to add a category or assign a category to a contact.  Using both Cardbook and CM.  I edit a contact and add a category, then save the contact.  The contact is saved and then (a couple of seconds later) is reverted to original status.  I'm also using "GcontactSync", to sync with my gmail contacts.
How to determine which of the addons is causing the problem?
How to add a category without using it (assigning it to a contact)?

**Comment by jobisoft** [comment]
Cardbook has nothing to do with my CatMan. CatMan is adding the category feature to the standard address book.

That being said, google sucks and does not allow to manage categories/groups/whatever via CardDAV. gContactSync is using a proprietary Google API to work with the google groups.

Dead end. Switch away from google to be free again.
