### ISSUE TITLE
Thunderbird 78 support

### ISSUE THREAD

**Issue by sergeyklay** [jobisoft/CategoryManager#51]
![image](https://user-images.githubusercontent.com/1256298/89561782-aca16480-d821-11ea-96e2-2d042b574f32.png)

---

Hello,

First I would thank you for such a wonderful extension. Thank you!

Thunderbird 78 is Mozilla's newest ESR (extended-support release), which comes out yearly and is considered the latest stable release.  Right now you can download the newest version from [the official website](https://www.thunderbird.net/en-US/), and existing users will be _automatically updated_ in the near future.

Right now, Thunderbird 78 support is not there, but it is extremely needed. Thus, I'd like ask to  provide this support.
Thank you,

--
Serghei

**Comment by jobisoft** [comment]
Could you give this version a spin?

[sendtocategory.zip](https://github.com/jobisoft/CategoryManager/files/5346635/sendtocategory.zip)

Feedback before being send to ATN would be helpful. Install the file using the gear icon on the add-on manager tab. No need to rename it to XPI.

**Comment by sergeyklay** [comment]
Hello. As I can see it works as expected. Thank you!

**Comment by fp66** [comment]
The (German) add-on description says the add-on is not yet compatible with Tb 78. Is this still correct, or has the description not been updated?

**Comment by jobisoft** [comment]
Which description? Can you provide a screenshot?

**Comment by fp66** [comment]
Sure!

![grafik](https://user-images.githubusercontent.com/53232385/96754906-3a78fe80-13d2-11eb-9320-a46b545bed93.png)

**Comment by jobisoft** [comment]
ah, that one. fixed. thanks!

**Comment by fp66** [comment]
Oh, this was fast - thanks!

By the way: Thanks a lot for your marvellous add-ons (TbSync & Co.)! I uses to work with gContactSync which doesn't run on Tb 78 anymore. But TbSync seems to be the modern alternative!
