### ISSUE TITLE
CategoryManager with Google labels for contacts

### ISSUE THREAD

**Issue by Pilkja** [jobisoft/CategoryManager#52]
Hi

I have the AddOn 'TbSync' with 'Provider for CalDAv & CardDav' installed, and syncing works fine for the Google contacts. I also have 'CategoryManager' installed but unfortunately the labels which I use in Google contacts for grouping (categorizing) my contacts are not imported - athough I expected that to happen.
What could be the problem here? What are the essentials to make it happen? Or is this not possible and did I misinterpret this possibility?

Thanks for helping!
Regards Jan

**Comment by jobisoft** [comment]
Google sucks. They do not announce groups via carddav and ignore any category settings.

**Comment by Pilkja** [comment]
So I can't use CategoryManager at all then? Not een with manual editing in TBird?

**Comment by jobisoft** [comment]
Sorry, no. Google did not implement the full cardav spec and wants to force you into their ecosystem using their proprietary protocolls. This is one of thr reasons why I moved away from them long ago. Try fruux.com.

**Comment by Pilkja** [comment]
Thanks for the information!
