### ISSUE TITLE
the category manager leads to persisent wrong phone number views

### ISSUE THREAD

**Issue by gerhardm5** [jobisoft/CategoryManager#54]
![image](https://user-images.githubusercontent.com/35499060/96130294-05633c80-0ef8-11eb-80a5-c7d75a4bec45.png)
when activating the category manager in TB78 it happens that almost all addresses are shown to have phone numbers (always the same) which are related to one other contact. Opening the contact this numbers are not mentioned. So the db is not crashed. it is only a problem on contact overview window.

**Comment by jobisoft** [comment]
Sure this is not an issue by some other add-on? Can you deactivate all others?

**Comment by gerhardm5** [comment]
yes, I can switch on and off the problem with category manager.

**Comment by jobisoft** [comment]
what version of CatMan?

**Comment by jobisoft** [comment]
We no longer manipulate the address book UI in version 6.2.
https://github.com/jobisoft/CategoryManager/releases/tag/v6.2
