### ISSUE TITLE
Compatible w/ TB  78.3.3

### ISSUE THREAD

**Issue by allenm28** [jobisoft/CategoryManager#55]
Just installed TB 78.3.3. Using TB Sync to sync addresses & calendar. Also then added category manager since it is now past September date.  Labels in Gmail which I assume are categories did not sync over.  Is the Catagory Manager operational?  If so how do I use?  I need to build 3 distribution lists that already exist in Gmail contacts.

**Comment by jobisoft** [comment]
gmail lists are not supported by tbsync, as that uses carddav and google does not send groups over carddav.

**Comment by allenm28** [comment]
Thank you


Allen M Rosenston
45 Prairie Park Dr. #409
Wheeling, IL 60090-2729

Tel: 847-459-6527
Fax: 847-459-6525
Cell: 847-347-8114
