### ISSUE TITLE
Google Contacts

### ISSUE THREAD

**Issue by fp66** [jobisoft/CategoryManager#56]
Hi,

are "categories" what Google Contacts calls "labels"?

![grafik](https://user-images.githubusercontent.com/53232385/96756590-917fd300-13d4-11eb-86c2-9dbfb1ba4f71.png)

If yes, TbSync doesn't manage to synchronize them to build appropriate address lists (groups). :-(

**Comment by jobisoft** [comment]
Sadly google sucks. They implemented only half of the carddav protocol and do not announce these groups via carddav. iCloud does. 

Edit: Assuming you are using TbSync and its CardDAV provider to sync your google contacts.

**Comment by sgordley1** [comment]
Hi, I can't see any difference in my TB address with or without Category Manager installed.  Using TB78, TbSync, and CardDAV.

**Comment by fp66** [comment]
> Edit: Assuming you are using TbSync and its CardDAV provider to sync your google contacts.

I think so. Is there any other way to sync Google Contacts to Tb?!

**Comment by hpbaum** [comment]
I do have the same problem with Google labels not being taken into account by Category Manager... with the new version.
It was doing it fine before. Since then, I had to start over with the sync and now not one group is synchronized.
I do hope you can fix it. In advance thank you very much.
