### ISSUE TITLE
Category manger height prevents address book window resizing

### ISSUE THREAD

**Issue by dugite-code** [jobisoft/CategoryManager#57]
The height of category manager list doesn't adjust when resizing the address book window.

This causes some user confusion when you have a long list of categories on initial start as the window can extend far below the monitor edge and you cannot resize to fit the monitor even when maximizing the window.

Un-resizable:

![2020-11-04 10_06_25-Window](https://user-images.githubusercontent.com/12742064/98060908-b882de00-1e85-11eb-85bd-f089035706be.png)

Resizable:

![2020-11-04 10_09_06-Window](https://user-images.githubusercontent.com/12742064/98061011-f1bb4e00-1e85-11eb-80c4-49b4126b12bf.png)

TB: 78.4.0 (32-bit)
OS: Windows 10 Pro

All toolbars re-set from safemode
All other addons except TbSync and Provider for CalDav & CardDAV were disabled

**Comment by jobisoft** [comment]
Fixed in TB91?

**Comment by dugite-code** [comment]
Yup, looks like it's all good in TB91
