### ISSUE TITLE
Question: AddOn rights for Category Mgr - "Full access"

### ISSUE THREAD

**Issue by michaelof** [jobisoft/CategoryManager#58]
Hi / Hallo John,

German or English, what's your preference? I'll start in English :-)

I'm using TB 78.4.0 on OpenSuse Leap 15.2, together with addons "TbSync" and "Provider für calDAV and cardDAV", to get my contacts, calendars and tasks synced from my Nextcloud on my VPS to my local TB. Among others.

As I more and more need categories, which are not synced from Nextcloud via cardDAV with the addons above only, I've found the hint for your addonn category manager.

But I'm somewhat surprised that your addon requests full access "Vollständiger Zugriff auf Thunderbird und Ihren Computer". Which neither "TbSync" nor "Provider für calDAV and cardDAV" (nor any other of my addons) are requesting.

Why does your addon needs this IMHO risky high access level?

Regards,
Michael

**Comment by jobisoft** [comment]
More info is here:
https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer

TbSync and the Provider requests this permission as well.

I landed a patch in Thunderbird a month ago, which shows this even after installation (which is not shown in 78 currently). I think this will land in the next point release of 78.
