### ISSUE TITLE
Option: Use full recipient list instead of BCC field

### ISSUE THREAD

**Issue by grb43** [jobisoft/CategoryManager#6]
Congratulations on CategoryManager. Its extremely useful.

The only drawback from my point of view is that the real recipient is not displayed in the "To:" field. I appreciate you have partially addressed the issue by allowing a default sender's address, along with a dummy display name, to be set in the preferences. However this is still not very helpful to the recipient and means the sender has to reset the preferences for each list that is sent.

Would it be possible to offer the more usual list handling procedure as an option to the current arrangement? It would make the add-on so much more useful for users working in less restrictive (enlightened?) domains.

**Comment by jobisoft** [comment]
What is a "more usual list handling procedure?" What do you mean?
- each rcpt has himself and only himself in TO? 
- for each category have a custom TO adress? Or autogenerate that TO address from the category name? 
- all rcpts are in TO and thus allowing all rcpts to see all email addresses? That is possible using the F9 menu when writing a new mail and using the catagory filter there and then click on ">> TO"

I have the first Option on my mind, but did not yet find an easy way...

**Comment by grb43** [comment]
Sorry for not being clear. I am used to having all recipients in TO as in your third option and didn't realize you could already do that with the F9 menu.

So my request is already covered, thank you.
