### ISSUE TITLE
Not able to see or create new category

### ISSUE THREAD

**Issue by ElephantInTheRoomFirst** [jobisoft/CategoryManager#61]
I have installed the category manager on 78.5.1 (32-Bit). 
It does not show, new or creat of category. 

![image](https://user-images.githubusercontent.com/28602840/101647676-4b8cd600-3a39-11eb-8e68-200dc858a854.png)

**Comment by jobisoft** [comment]
Those things are now done directly on a contact context menu or contact edit dialog.

**Comment by ElephantInTheRoomFirst** [comment]
Thank you. Previous category creation was easy. But this is acceptable.
