### ISSUE TITLE
How to get category manager 4.1 in Thunderbird 78.7.1 working

### ISSUE THREAD

**Issue by xtrailrunner** [jobisoft/CategoryManager#66]
I would like to sync my Google address book including labels with my TB address book. I have installed the newest version of category manager, TbSync 2.21 and Google-4-TbSync. I can sync my contacts but no labels or categories are created locally.
The software seems to be in a very early stage. What is your recommendation? 
Regards Juergen

**Comment by jobisoft** [comment]
Isn't google-4-tbsync loading labels as mailing list entries below the address book? can you ask the developer of that provider what is to be expected?
