### ISSUE TITLE
Button zum Ausblenden der Kategorien

### ISSUE THREAD

**Issue by Ogolar** [jobisoft/CategoryManager#7]
Nachdem ich ca 15 Adressbücher und 50 Kategorien habe wäre es eine echte Hilfe wenn es möglich wäre das Kategorienfenster nach unten in die Benachrichtungsleiste Verschwinden zu lassen, ähnlich wie z.B. bei lightning den Tagesplan.

Denn sonst ist entweder der Bereich für die Adressbücher oder der Bereich für die Kategorien immer zu klein.

**Comment by jobisoft** [comment]
Der Seperator zwischen Adressbuch-Liste und Kategorie-Liste kann man verschieben (rauf/runter). Wenn man ihn ganz nach unten fährt, wird die Kategorie-Liste ausgeblendet. Hilft das evtl schon?

**Comment by Ogolar** [comment]
Das ist schon gut. Allerdings wäre es schön wenn das mit einem Klick erledigt wäre und man sich das "geschiebe" sparen kann. 
Ich brauche das ca. 10 mal am Tag, daher wäre ein mit einem Klick nach unten verschwinden und mit einem Klick in der vorheringen Größe wieder herstellen sehr erleichternd.

**Comment by jobisoft** [comment]
Bitte mal die aktuelle version aus dem repository anschauen. INSTALL.md enthält eine Anleitung.

**Comment by Ogolar** [comment]
Top! Funktioniert vielen Dank. 
Werde noch ein wenig Testen. Wenn es in den Produktiveinsatz geht kommt eine Spende.
