### ISSUE TITLE
Tb 91: All Categories marked

### ISSUE THREAD

**Issue by PunchIng** [jobisoft/CategoryManager#70]
After updating to Tb 91 I see all categories marked at all contacts. I can remove and set tickmarks - but can't see the categories marked before...
![Category Manager](https://user-images.githubusercontent.com/30384727/131317822-34512880-7ad1-4192-99b3-4717124b71a4.jpg)

**Comment by jobisoft** [comment]
Fixed by https://github.com/jobisoft/CategoryManager/commit/26ae1572c343ea0b506494cf5813d0bda933ad36
