### ISSUE TITLE
Address transfer in recipient field fails

### ISSUE THREAD

**Issue by Detlef-AC** [jobisoft/CategoryManager#72]
When I drag all or multiple selected addresses of a category into the recipient field of a mail, tb hangs. This is a new phenomenon since a few weeks. How can this be avoided?

tb 91.3.0 (64-bit), Category Manager 5.0

**Comment by mMuck** [comment]
Can't reproduce this. Solved?
TB 91.5.1 (64-Bit) @ win10, Category Manager 5.1

@Detlef-AC Did you drag and drop contacts from the addressbook window or from the contacts sidebar to the compose window?

**Comment by jobisoft** [comment]
With CategoryManager v6.2 we no longer live inside the address book or manipulate its UI.
