### ISSUE TITLE
Editieren/ Neu Anlegen von Kategorien nicht möglich

### ISSUE THREAD

**Issue by uelpenich** [jobisoft/CategoryManager#73]
Thunderbird bringt ab Version 91.?? eigene caldav und carddav Mechanismen mit. 
Der Category Manager funktioniert nicht mit den Thunderbird CardDAV Adressbuch. Angelegte Haupt- und Unterkategorie werden nicht angelegt und gespeichert. 
![grafik](https://user-images.githubusercontent.com/63613798/142761292-ac8a56e5-ee78-4996-bbd3-275c6b6929d6.png)

**Frage**: Kann der>Provider für CalDAV & CardDAV sowie TbSync mit den Thunderbird eigenen xxxDAV's koexistieren, sodass ich den Adressbucheinträgen Kategorieen zuordnen kann?

**Comment by jobisoft** [comment]
Der native CardDav support synced das benötigte Feld nicht mit deinem Server.

Du musst dich entscheiden, entweder benutzt du den nativen Support, oder TbSync.
