### ISSUE TITLE
Can't see any categories or edit them in contact

### ISSUE THREAD

**Issue by superaddi** [jobisoft/CategoryManager#74]
Hello,
I tried several times to use the categorymanager. I'am using google labels for some grouping. As my thinking I should see this labels in my contacts under categories. The contacts have fields for categories, but they are empty and not editable. I'am using:
Thunderbird: 91.3.2 (64-Bit)
Category Manager: 5.1
Provider für CalDAV & CardDAV: 2.0.2
TbSync: 3.0.1
and no other add-ons

**Comment by jobisoft** [comment]
Google is not supported.
