### ISSUE TITLE
contact, renaming catergories

### ISSUE THREAD

**Issue by myw00** [jobisoft/CategoryManager#75]
Hi. First, it says that "send me an email" is an option if the user has an issue, but I don't see your email noted anywhere.
Second, how does one rename a category? When I right click on a category name in the "Filter contacts by categories" window in the Address Book, the options "rename category," "delete category," "edit category directly," and "import/export category" are all greyed out.
Third, in the "Introduction" section of the F.A.Q. page, there is a bulleted list after the sentence, "They are described in detail in the following pages," but none of the items on this list are "clickable," i.e., they aren't linked to anything.
What am I missing?
Thanks,
Moshe Wisnefsky

**Comment by jobisoft** [comment]
You cannot change names if you have the global address book selected. You must select a specific address book and then you should be able to rename categories.

And you are correct, I hade no time yet to fill in the missing help pages.
