### ISSUE TITLE
On Linux Mint 20 - Adressbooks Window to small and not able to adjust

### ISSUE THREAD

**Issue by stefan-franz** [jobisoft/CategoryManager#76]
Hello, on Linux (newest Thunderbird version) the adress book is not scalable to show all adress books. 

![18153-bildschirmfoto-vom-2021-12-28-20-39-17](https://user-images.githubusercontent.com/96744684/147873081-412dfb50-231b-4cda-82c8-eaacd1731f59.png)

**Comment by stefan-franz** [comment]
Is anyone here?

**Comment by jobisoft** [comment]
Yes, but no resources/time at the moment.

**Comment by stefan-franz** [comment]
Hello, i would polite ask again...maybe you find time in the next weeks to fix it. Would be great - and would very thankful. 
Kind regards, Stefan

**Comment by stefan-franz** [comment]
Hello, i'd like to ask from time to time....maybe you have time to fix it now. 
Would be great. 
Best wishes, Stefan

**Comment by jobisoft** [comment]
I will look at it when I prepare the release for TB102

**Comment by jobisoft** [comment]
The new version is not injecting into the address book UI anymore.
