### ISSUE TITLE
Mail compose: Handling of contacts with no mail address

### ISSUE THREAD

**Issue by mMuck** [jobisoft/CategoryManager#77]
I have some contacts without mail address like some kids (to remember the birthday) or grandma w/ only a telephone number. I think this isn't that uncommon. They are in my "family" category.
For example this contact list/filtered category content
`Grandma (no mail address)`, `Sister sister@family.org`, `Son (no mail address yet)`
results in 
![grafik](https://user-images.githubusercontent.com/8143240/152995322-109713d3-dd11-46de-998a-0da22f7a7dab.png)
TB doesn't filter that out before sending. It shows an error and it must be corrected manually.
It would be a good thing to filter out contacts without mail address from a selected category before adding them to the recipients list(s).

BTW A drag and drop action results in a joined recipient list `Grandma,Sister <sister@family.org>` and `Son <>`.
This could result in wrong contact info and potentially leak some unwanted information. I imagine the use in a BBC field or my sister thinks I call her my Grandma Sister in my contacts - that could get very serious and dangerous... 💀 
Could this topic originate from TB itself? The same happens to drag and drop contacts from the address book window. Perhaps it's not related to Category Manager?

TB 91.5.1 (64-Bit) @ win10, Category Manager 5.1

**Comment by jobisoft** [comment]
Fixed in v6.2.
https://github.com/jobisoft/CategoryManager/releases/tag/v6.2
