### ISSUE TITLE
Blank category list

### ISSUE THREAD

**Issue by scandalxk** [jobisoft/CategoryManager#78]
I'm trying to use CategoryManager with Thunderbird 91.6.0 (64 bit) on a Windows 10 PC.  My contacts are on a Microsoft Exchange Server, which I am connecting with Owl for Exchange.  I have about 1,000 contacts, almost all of which have at least one category, usually the name of a project we have worked on together.  Many contacts have several categories, for example where we have worked on more than one project together.

All the contacts are listed, without the categories.  As I understand it, the list of categories should appear in the lower left of the Address Book view, but it is blank.  I can add a category in the "Categories" tab in the contact details, or by right-clicking on a contact in the list and choosing the "Categories" pop-up, but if I add a category to a contact here, it is not synced to Exchange.

Is this expected behaviour?  Does this Add-on not support Exchange?  Or am I missing something?

**Comment by jobisoft** [comment]
CategoryManager was designed to work with local address books and address books managed by TbSync (Exchange Active Sync, CardDAV). 

I assume the OWL add-on does not know about the category property used by the CategoryManager and thus does not sync it to your server. Nothing I can do here. You might ask them to support the Categories field. Or use TbSync for your contacts, but OWL is more powerful.

**Comment by scandalxk** [comment]
OK, thank you Jobisoft for replying so promptly.  Maybe I'll get in touch with Owl.

Thanks also to Microsoft for "retiring" Outlook 2010 yesterday morning, without any warning or notice that I saw.  :-/
