### ISSUE TITLE
Editieren/ Neu Anlegen von Kategorien nicht möglich

### ISSUE THREAD

**Issue by Ogolar** [jobisoft/CategoryManager#8]
Ich bekomme alle Kategorien schön angezeigt. Allerdings kann ich weder neue Kategorien anlegen (der Button ist ausgegraut) noch Kategorien bearbeiten oder löschen (ebenfalls ausgegraut)

**Comment by jobisoft** [comment]
Wenn das "Hauptadressbuch" selektiert ist (Alle Adressbücher) dann sind die Funktionen nicht verfügbar, weil nicht klar ist, welches Adressbuch bearbeitet werden soll (es könnten zum Beispiel in zwei Adressbüchern gleiche Kategorien enthalten sein).

Es muss zuerst ein bestimmtes Adressbuchg ausgewählt werden, damit es bearbeitet werden kann.

Löst das ihr Problem?

**Comment by Ogolar** [comment]
Perfekt, habe ich gerade eben auch entdeckt! Danke für den Tip
