### ISSUE TITLE
Thunderbird categories not working with built-in CardDAV? 

### ISSUE THREAD

**Issue by mdonz** [jobisoft/CategoryManager#80]
Hi 
thanks for all your great work around Thunderbird (TB) and TB add-ons. We see these add-ons as essential to make TB a more competitive email client (to Outlook) in the business world.
A CalDAV/CardDAV server backend (we use SOGo for our customers) with a good TB setup (with add-ons) makes TB a very good solution from our perspective.
We have tested various TB "DAV add-ons" in recent years (with TB going through various version upgrades) from SOGo-Connector, CardBook, TB-Sync (plus provider for CalDAV&CardDAV) and are now trying to achieve the required functionality (Server based address books and calendars) with TB's builtin DAV tools (since TB version 91). 
Although CardDAV is working, I find that I cannot add categories with this add-on (CategoryManager) as I can do with a local TB addressbook. Is this the right place to report this? 
Also, where would be the best place to ask general questions re the required DAV add-ons? Where to compare and especially whether TB DAV add-ons might even be needed since the built-in DAV tools? 
My personal preference has been CardBook for a long time but I am looking at going back to a TB setup with as few as possible add-ons and using TB's core functionality wherever possible. Thanks
P.S.: Gruesse vom Ex-Koelner in Neuseeland ;-)

**Comment by jobisoft** [comment]
It looks like the native CardDAV implementation does not sync the CATEGORIES field. I guess that will be added in the future. As long as that is not the case, you will need to keep using CardBook or TbSync.
