### ISSUE TITLE
Category Manager is incompatible with Thunderbird 100.0.

### ISSUE THREAD

**Issue by skrap** [jobisoft/CategoryManager#82]
Thunderbird is readying the latest ESR, which I believe will be based on Thunderbird 102.  Category Manager is incompatible with the current versions of thunderbird beta.  Is this just a matter of incrementing the max version?

![image](https://user-images.githubusercontent.com/1132698/164517292-5cc0b2f8-b159-49b5-a689-a8e5966555ec.png)

**Comment by charabaruk** [comment]
Thunderbird 102 is now available and is indeed the new ESR.

**Comment by jobisoft** [comment]
I am currently swamped with work. I will see what I can do.

**Comment by herzogmedia** [comment]
just fyi: the new version does have support for carddav natively (see jobisoft/TbSync#591) but this does not seem to include categories.

**Comment by stefan-franz** [comment]
I hoped the new thunderbird adressbook can categories per default - but as your comments read - it's not. 
What a pity. Makes it sense to post anywhere a wish for improving the next versions? If yes: Where can i do it?

**Comment by e-jim** [comment]
> I hoped the new thunderbird adressbook can categories per default - but as your comments read - it's not. What a pity. Makes it sense to post anywhere a wish for improving the next versions? If yes: Where can i do it?

@stefan-franz : I opened a feature request on Bugzilla some time ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1764184
I'm not sure it is the most efficient way to communicate one's whishes, but at least it leaves a trace.
You could maybe vote for it to make it weight more.

**Comment by Michele67tn** [comment]
Any news regarding the update of category manager to be compatible with thuderbird 102? Please John, please update!

**Comment by PhilippeAccorsi** [comment]
Can we have a garantee that new version of Thunderbird with carddav use category like this module ?
Some of users use this module and I don't want to update thunderbird with risk of decrease feature used.

**Comment by stefan-franz** [comment]
No, the version 5.1 (the current version) works only with Thunderbird 91.X - not with 100 or newer. I hope too - that john has time to update this great Add-On - or better would, if Thunderbirds Adress Book per default would have the category function. I don't now why the development team, does it make.

**Comment by ryliejamesthomas** [comment]
> > I hoped the new thunderbird adressbook can categories per default - but as your comments read - it's not. What a pity. Makes it sense to post anywhere a wish for improving the next versions? If yes: Where can i do it?
> 
> @stefan-franz : I opened a feature request on Bugzilla some time ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1764184 I'm not sure it is the most efficient way to communicate one's whishes, but at least it leaves a trace. You could maybe vote for it to make it weight more.

The categories I already had seem to display, but I still can't add or edit the category field. If a category exists you can add people to it by right-clicking on it, selecting 'Properties', and manually entering the email address. You can even send a message to everyone in a category by selecting all the names and selecting 'write'.

So it's not really complete, but hopefully getting there.

I only just moved to a version with the new address book, so this might be a recent change.

**Comment by jobisoft** [comment]
Can you share a screenshot of how the categories are displayed in the new address book?

**Comment by ryliejamesthomas** [comment]
![screenshot_22-09-17_19-01-52](https://user-images.githubusercontent.com/25972447/190849198-49d3f7a0-80eb-4fb2-bd3c-a35dca3af27d.png)

Even has a relevant icon.

This is an address book on my CardDAV server.

(unrelated to this add-on, but maybe useful to someone reading: I tried moving contacts with categories from the address book they were in to another and now they don't have categories)

**Comment by ryliejamesthomas** [comment]
Oh, this is a list, not a category. Sorry for the mix-up.

**Comment by stefan-franz** [comment]
Hello, can anyone confirm, that the Thunderbird 102 adressbook has categories? Or is there anywhere an add-on who can display it? 
My Linux Mint wants to update to Thunderbird 102 and i think i can not back if i do it - and categories for my are extreme important.

**Comment by stefan-franz** [comment]
Shit - Auto update to Thunderbird 102.2.2 - and no Categories in the Adressbook. 
Please John make your Categoriy Manager to work with 102.2.2
Thanks in Advance.

**Comment by thomas-mgh** [comment]
> **@stefan-franz:** Hello, can anyone confirm, that the Thunderbird 102 adressbook has categories? Or is there anywhere an add-on who can display it?

You may check if CardBook does comply with your needs.

**Comment by jobisoft** [comment]
We are approaching this two-fold:
1. There is someone working on the update of CategoryManager for 102
2. Thunderbird core is working on bringing categories to the address book. Do not know if it can be backported to 102. Work has just started.

**Comment by stefan-franz** [comment]
Thank you very much. Great news.

**Comment by ingo-b** [comment]
Hi there, I appreciate that too! I can't wait for the new version as I need CategoryManager to handle my adresses. Thanks a lot in advance.

**Comment by stefan-franz** [comment]
Hello, is there already a solution for categories in 102? My problem: With update to Linux Mint Cinnamon 21. the update routine installs the thunderbird version 102. And i organize all my contacts with categories.

**Comment by jobisoft** [comment]
There is work being done by @kxxt. [Milestone-1](https://github.com/jobisoft/CategoryManager/pull/85) of 4 has been completed. After Milestone-2 we might be able to release preview versions.

Throw money at kxxt: https://www.paypal.me/tokxxt

**Comment by stefan-franz** [comment]
Thank you - i've just sent some money.

**Comment by Michele67tn** [comment]
Is there any news about the development of Category Manager for Thunderbird 102?

**Comment by kxxt** [comment]
> Is there any news about the development of Category Manager for Thunderbird 102?

I am working on it. But I am just an undergraduate with lots of course work to do and exams to prepare, so there is little development activity recently. 

I will have some spare time in the upcoming winter holiday.  You can expect a new release in January or February, but I can't guarantee it to you.

**Comment by jobisoft** [comment]
Closing this in favour of 
https://github.com/jobisoft/CategoryManager/issues/87#issuecomment-1373860202

It is time to check out the pre-release!

**Comment by stefan-franz** [comment]
Does ist work on Linux Mint 21 too with categories?

**Comment by jobisoft** [comment]
It should, give it a try!

**Comment by stefan-franz** [comment]
In the package management of Linux Mint 21 is the 102.4.2 - from which version number can Thunderbird categories?
I will replay after this version is in the package management so that i'm able to install it.

**Comment by jobisoft** [comment]
We need 102.6 because we use context menus and there was a bug in Thunderbird where context menus for add-ons did not work. Fixed in 102.6. It is a pity that Linux distros ship old versions. There has been a severe data loss issue in an 102.2 or so and Linux distros did not ship the update for weeks and just let their users hanging (and caused preventable data loss). I just do not understand why they do that.

You can install Thunderbird directly from thunderbird.net and get auto-updates.

**Comment by stefan-franz** [comment]
Over PPA I installed the 102.6.1. 
But can't find category's ....Hmmm....

**Comment by jobisoft** [comment]
Have you looked at the release notes? Our UI changed a lot
https://github.com/jobisoft/CategoryManager/releases/tag/v6.1

I am in the process of releasing v6.2 which fixes a few bugs.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/CategoryManager/releases/tag/v6.2

**Comment by stefan-franz** [comment]
So i need your new category manager? (thought thunderbird can in the future per default categories.....)
I install it, if i can see the entry in the addons search of TB 102.6.1 (at the moment not findable with the search)

**Comment by jobisoft** [comment]
We have not yet released CategoryManager v6.* to ATN, only here on GitHub. 

Thunderbird does not yet support Categories, that is why we updated this add-on for TB102.

**Comment by stefan-franz** [comment]
I hope thunderbird can do this by default someday - for the developers to see the sense: With the category function my 4000 business contacts can be perfectly organized incl. resubmission for customers etc. 

Without the category function I could not use it at all. 

In my case I stay with TB 91 because here everything runs and I had found a way how Linux Mint does not update to the new version. I really hope that in TB this will be built in at some point for a nice and uncomplicated operation. 

I think of my sales team who are partly technically not so very fit, so they can't manually build in something (like the new plugin version). That with the old 91 everything works we stay for now and will donate something to TB again if TB can do it by default. 

Thanks for your work and hopefully you can influence here that it is implemented.

**Comment by jobisoft** [comment]
You subscribed to the github issue and that is why you get first hand notifications, even before the official release. We will release CatMan v6 to ATN probably next week, when we have received more feedback, that everything works (it would be nice to know if it works with your address book and categories).

If your Linux distro updated to 102.6 then I really suggest to update your installs, instead of staying on TB91, which is EOL and does not receive security updates.

**Comment by stefan-franz** [comment]
I give you of course a feedback - i have one test device for this and check it out. 
If it works, i can update. - if not, i would here give you feedback, as i do with Ardour, Mixxx, Zoom for Linux (in that develepment i'm involved as a tester / with the view as a user.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/CategoryManager/releases/tag/v6.3

**Comment by jobisoft** [comment]
Shipped: https://addons.thunderbird.net/addon/categorymanager/

**Comment by stefan-franz** [comment]
It works - but the workflow is a big step backward......

I use the categories for resubmission of customer. E.g. i call from one category one customer after the other and add some information or change the category. In V 91 a fine workflow - now in 102 two steps. I hope that can in the future improved - i can't use it so.

**Comment by jobisoft** [comment]
You mean you do not see the contact information of the contacts which are in the category? 

I assume @kxxt could implement an on-click action, which shows an overlay with the details of the clicked contact. He still has to decide to take over the development of the add-on and spend time on new features (without being paid by me, but purely funded by user donations).

**Comment by stefan-franz** [comment]
in the adressbook there is no entry of the category - to adjust the category i have to click on the categorymanager to select the contact with right click and adjust the category. 
I find the workflow in TB 91 with your great plugin fine and for business perfect. This  solution for TB 102 i don't want to use - double time and double error quote to forget the 2nd step. 
In TB 91 i edited the contact in one step, and changed the category - was fine for me.

**Comment by jobisoft** [comment]
We currently cannot get into the address book UI. What we can offer is to move the entire workflow into the category manager.

- Browse category
- click contact (see details, which currently is not implemented) and do call
- context click to remove "done" contact from category
- move to next contact

If that is not a fit, then I do not see another way to get this working for you.

**Comment by stefan-franz** [comment]
Thanks for your offer - but for a good workflow in my eyes there need to be all information of a contact and the possibility to edit all in one mask. 
Maybe you can get the development team that TB can categories by default in the future. 102 is for me a back step from 91.

**Comment by kxxt** [comment]
> I assume @kxxt could implement an on-click action, which shows an overlay with the details of the clicked contact. 

That's an easy job. In addition to that, perhaps we can add a few checkboxes(like the following four) to let the user select what they want to display.

- [x] Name
- [x] Email
- [x] Phone Number
- [x] Address

> He still has to decide to take over the development of the add-on and spend time on new features (without being paid by me, but purely funded by user donations).

Hi @jobisoft, I don't think it is time for me to take over the development now. I will contribute pull requests when I have time. But I am too busy to maintain this add-on.
