### ISSUE TITLE
Howto export/import CATEGORIES?

### ISSUE THREAD

**Issue by Ypot** [jobisoft/CategoryManager#83]
Is it possible to import and export CATEGORIES in ThunderBird?

Your addon is great, but I can't import vCard 4.0 CATEGORIES and that makes CategoryManager to lose robustness.

**Comment by jobisoft** [comment]
That is tricky. The add-on is from an age, where Thunderbird did not support CardDAV or vCard 4.0. The categories are stored in a simple property. You can export them using the export function of the CategoryManger into a CSV file, I think.

You find the export function in the context menu of each category in the left category list in the address book of Thunderbird 91.

For Thunderbird 102, I have not yet found a way to make the CategoryManager compatible, but IF I get it working, I will migrate the category information into the vCard Categories field.

**Comment by Ypot** [comment]
You are right, it can export to CSV.
I hope ThunderBird gets some support for "Categories" in future versions.

Thanks for your nice work.
