### ISSUE TITLE
Category Manager is incompatible with Thunderbird 102.6.1

### ISSUE THREAD

**Issue by Easy7985** [jobisoft/CategoryManager#87]
Hello
I tryed to Install the add-on in TB102.6.1. Systems showes that  CategoryManager AddOn is incompatible th runng version.

Is this problem expected to be solved?

Is there an known workaround to get CategoryManager installed to be tested? 

Thank

**Comment by jobisoft** [comment]
There is work being done on a new version. We may release a preview next week.

**Comment by Easy7985** [comment]
Thanks!



schöne Grüße

Horst-Dieter Büchner
Eichenweg 25
96242 Sonnefeld
Tel 09562/579062
Bitte denken Sie an die Umwelt bevor Sie diese E-Mail drucken.



-------- Ursprüngliche Nachricht --------
Von: John Bieling ***@***.***>
Datum: 02.01.23 12:48 (GMT+01:00)
An: jobisoft/CategoryManager ***@***.***>
Cc: Easy7985 ***@***.***>, Author ***@***.***>
Betreff: Re: [jobisoft/CategoryManager] Category Manager is incompatible with Thunderbird 102.6.1 (Issue #87)


There is work being done on a new version. We may release a preview next week.

**Comment by christophvoelker** [comment]
Sounds wonderful!

Many greetings,
Christoph

**Comment by cvosoft** [comment]
> There is work being done on a new version. We may release a preview next week.

Sounds wonderful!

Thanks and many greetings,
Christoph

**Comment by jobisoft** [comment]
Here is a pre-release: 
https://github.com/jobisoft/CategoryManager/releases/tag/v6.1

Please try it with a data set where you have a backup. Feedback is very much appreciated.

**Comment by cvosoft** [comment]
I am using Ubuntu 22..4.1 and TB 102.4.2 and downloaded the pre-release zip file, but I can't install this add-on from file in TB ("nicht kompatibel")...

Greetings, Christoph

**Comment by jobisoft** [comment]
Yep, you need 102.6.

**Comment by cvosoft** [comment]
Okay, it seems that the Addon only shows my local adressbook and not the remote CardDav Book ...

**Comment by jobisoft** [comment]
How is your remote CardDav Book connected? Using CardBook or Thunderbirds native CardDav support?

**Comment by cvosoft** [comment]
Thunderbirds native CardDav support.

**Comment by cvosoft** [comment]
Should I use CardBook? I didn't know that add-on before ...

**Comment by cvosoft** [comment]
My goal would be to synchronize "email lists" over Nextcloud somehow ...

**Comment by jobisoft** [comment]
No, I wanted to make sure that you do not use that add-on, because Thunderbird cannot see its books.

So I checked and it works for me. Could you post a screen shoot, where you see it is not showing your address book? Just so I can see what you see?

**Comment by cvosoft** [comment]
![1](https://user-images.githubusercontent.com/82140472/211060324-5c752c0f-3f47-4eba-b7d3-aa54a73f13fe.png)

**Comment by cvosoft** [comment]
"Kontakte" ist my CardDav Book.

Regarding a screenshot of the "CategoryManager window": When I press "Druck" on the keyboard, this window closes automatically and afterwards the screenshot is done.

**Comment by jobisoft** [comment]
Here is my setup:
![image](https://user-images.githubusercontent.com/5830621/211060597-d37f4001-12af-4c11-91a7-700fbc8ecd55.png)

And this is how it is shown by my add-on:
![image](https://user-images.githubusercontent.com/5830621/211061063-2c6f767c-51f0-47a1-ae23-c734cb956027.png)

**Comment by cvosoft** [comment]
I try to find another way to make screenshots ...

**Comment by jobisoft** [comment]
As written in the release statement, the CategoryManager no longer sits in the Address Book, but behind two buttons, one in the message composer and one in the main Thunderbird window. With Thunderbird 115 we will be able to place a button into the address book as well, I hope.

**Comment by cvosoft** [comment]
![2](https://user-images.githubusercontent.com/82140472/211061865-18608027-ccb3-4d9b-9a89-170c76913515.png)

**Comment by jobisoft** [comment]
And how does it look in my add-on?

**Comment by cvosoft** [comment]
As I said, when I press my "Print" Button on the keyboard this add on window closes immediatly before a screenshot is done. Let me try to find another way to make screenshots

**Comment by cvosoft** [comment]
![3](https://user-images.githubusercontent.com/82140472/211062675-f9693ca8-b5ed-4751-8dc2-82820088bad0.png)

**Comment by cvosoft** [comment]
I have to use a "delay" when making a screenshot :)

**Comment by jobisoft** [comment]
Uff, that is strange. Do you see anything on the error console? Extras ->  Entwickler-Werkzeuge -> Fehlerkonsole ?

Please also disable and re-enable the add-on and look at what is going on the console.

**Comment by cvosoft** [comment]
Sorry, I just simply restarted TB and it seems to work.

**Comment by cvosoft** [comment]
"Have you tried turning it off and on again?" :)

**Comment by cvosoft** [comment]
I tried to add categories and then write an Email (BCC) to all from one category - it looks good!

**Comment by cvosoft** [comment]
So for my needs no other Add-On is needed, right? No TbSync etc.? Only the CatMan?

**Comment by jobisoft** [comment]
> Only the CatMan?

Yes.

**Comment by kxxt** [comment]
> Okay, it seems that the Addon only shows my local adressbook and not the remote CardDav Book ...

This bug could only happen if you created a new address book. Currently Category Manager doesn't show newly created address books. We will fix it.

**Comment by jobisoft** [comment]
We released v6.2 which add listeners for new address books:
https://github.com/jobisoft/CategoryManager/releases/tag/v6.2

There is still a bug that contacts of newly added CadDAV address books are not seen. This is a bug in Thunderbird which we will report and fix soon.

**Comment by thomas-mgh** [comment]
Thank you very much for your work! I tried version 6.2 with my remote CardDAV-Addressbook stored in Nextcloud. Category Manager works, but for some data records comes the message "No email found" although there is an e-mail-address stored in my addressbook. 
An other problem is, that I didn't find an opportunity to add or edit categories.

**Comment by jobisoft** [comment]
Add/edit categories is done via context menus on contacts or categories. Can you confirm?

Can you provide a vcard of a contact where we show "no email address" ?

**Comment by thomas-mgh** [comment]
I can confirm that add/edit categories is possible via context menus. I will send you a vcard where "no email address" is shown by PM.

**Comment by thomas-mgh** [comment]
I don't know why, but the message "No email available" doesn't appear any more.

Formerly you could write the name of a category in the To-Field of Thunderbird and all addresses with this category where inserted automatically. In version 6.2 of CM you can insert the addresses by the context menu only. It is not essential but would be very helpfull if this former feature could be implemented in CM again.

**Comment by jobisoft** [comment]
> I don't know why, but the message "No email available" doesn't appear any more.

It depends on the flavour of the vCard. I found the issue and it is fixed and will be released in v6.3 in a few hours

**Comment by jobisoft** [comment]
https://github.com/jobisoft/CategoryManager/releases/tag/v6.3

**Comment by jobisoft** [comment]
> Formerly you could write the name of a category in the To-Field of Thunderbird and all addresses with this category where inserted automatically. 

I do not think that is true. Only address lists were auto-completed, but not my categories.

> In version 6.2 of CM you can insert the addresses by the context menu only. It is not essential but would be very helpfull if this former feature could be implemented in CM again.

You can double click on the category name, which will pick the BCC option and create the message.

**Comment by thomas-mgh** [comment]
> > Formerly you could write the name of a category in the To-Field of Thunderbird and all addresses with this category where inserted automatically.
> 
> I do not think that is true. Only address lists were auto-completed, but not my categories.

Indeed, the addresses where not auto-completed. What I meant was that you could type a catagory name into the To-Field (or CC or BCC) of TB. Then the input changed from "category" to "category<"category">" or you could select this entry, if it was not unique. Then the e-mail was sent zu all addresses with this category. This function was useful but not essential. Using the context menu works as well. Thank you for your work!

**Comment by jobisoft** [comment]
A general request: Have you all checked version v6.3? Is everything working for you? Are we in a position to ship it via the Thunderbird add-on store to everybody?

> Indeed, the addresses where not auto-completed. What I meant was that you could type a catagory name into the To-Field (or CC or BCC) of TB. Then the input changed from "category" to "category<"category">" or you could select this entry, if it was not unique

I really do not think my add-on did that. I checked its code for TB91 and [here](https://github.com/jobisoft/CategoryManager/blob/TB91/sendtocategory/background.js#L27-L41) you can see that I do not manipulate the message compose window. So there is no CatMan code running there. Do not know however, if I did that in earlier versions.

I might use a virtual address book in the future to add a feature like that, but currently it is not possible.

**Comment by thomas-mgh** [comment]
I installed version 6.3 and from my point of view it is ready to be shipped via the Thunderbird add-on store.

**Comment by jobisoft** [comment]
Shipped: https://addons.thunderbird.net/addon/categorymanager/

**Comment by Easy7985** [comment]
..thanks for this graet performance and cooperation to all of thouse being involved in that issue!


schöne Grüße

Horst-Dieter Büchner



-------- Ursprüngliche Nachricht --------
Von: John Bieling ***@***.***>
Datum: 10.01.23 15:14 (GMT+01:00)
An: jobisoft/CategoryManager ***@***.***>
Cc: Easy7985 ***@***.***>, Author ***@***.***>
Betreff: Re: [jobisoft/CategoryManager] Category Manager is incompatible with Thunderbird 102.6.1 (Issue #87)


Closed #87<https://github.com/jobisoft/CategoryManager/issues/87> as completed.
