### ISSUE TITLE
ICloud contact categories?

### ISSUE THREAD

**Issue by ed1111** [jobisoft/CategoryManager#94]
Is it still no longer possible to sync iCloud contacts and their iCloud categories with Thunderbird using TBSync, Category Manager or any other way?  (I think this was previously possible using mailing lists.)

Thanks.

**Comment by stefan-franz** [comment]
Yes - unfortunately TB 102 was in my eyes a great step backwards. 

I use TB 91 because i need the categories

**Comment by jobisoft** [comment]
The CategoryManager has been released for TB102+
https://addons.thunderbird.net/en-US/thunderbird/addon/categorymanager
