### ISSUE TITLE
Catogry Manager not working under Thunderbird 102.6.=

### ISSUE THREAD

**Issue by GoeWink** [jobisoft/CategoryManager#95]
I used Category Manager for Long till Thunbderbird 98. Bow I found a compatible version again. But installing down not work. Why? Are caegories no longer provided in TB 102=

**Comment by jobisoft** [comment]
Hi,

CatMan has been updated:
https://addons.thunderbird.net/en-US/thunderbird/addon/categorymanager/

It works differently now. See descriptions here:
https://github.com/jobisoft/CategoryManager/releases/tag/v6.3

Does it work for you?
