### ISSUE TITLE
Description / F.A.Q. Incorrect or Incomprehensible

### ISSUE THREAD

**Issue by gohrner** [jobisoft/CategoryManager#98]
The only (official) description of CategoryManager I could find was in the FAQ section here on GitHub:

https://github.com/jobisoft/CategoryManager/wiki/F.A.Q.

It states:

> The Add-On also adds a couple of functions to the thunderbird address book, to create and manage categories. They are described in detail in the following pages:
> 
> * Manage categories from within the address book
> * Manage categories in the contact edit dialog
> * Access categories via the contact sidebar

So far, so good - unfortunately, I have been unable to find the abovemention "following pages" which are supposed to describe these features in detail.

I also was not able to find these feature without documentation / an explanation.

What I found was a "Catogies" button in the extension button bar(s) which shows categories and its contents, but I could not find any official documentation about this anywhere, neither on the Thunderbird AddOns page, nor here on GitHub...

**Comment by jobisoft** [comment]
I removed the wiki. Documentation is only what is on ATN:
https://addons.thunderbird.net/addon/categorymanager/

**Comment by PanderMusubi** [comment]
Can you also remove the link from the README.md to https://github.com/jobisoft/CategoryManager/wiki/F.A.Q. on this line https://github.com/jobisoft/CategoryManager/blame/TB102/README.md#L10

**Comment by gohrner** [comment]
@PanderMusubi: Not sure if a closed issue is considered / monitored, better create a new issue.

**Comment by jobisoft** [comment]
Done.
